In [0]:
displayHTML("""
<div style="text-align:center; width:100%;">

<h1><b>UNIVERSIDAD NACIONAL TORIBIO RODRÍGUEZ DE MENDOZA DE AMAZONAS</b></h1>

<img src="https://upload.wikimedia.org/wikipedia/commons/9/95/Logo-2016-solo-ok.png" width="150">

<h3><b>FACULTAD DE INGENIERÍA ZOOTECNISTA, BIOTECNOLOGÍA, AGRONEGOCIOS Y CIENCIA DE DATOS</b></h3>

<h3><b>ESCUELA PROFESIONAL DE INGENIERÍA EN CIENCIA DE DATOS E INTELIGENCIA ARTIFICIAL</b></h3>

<hr>

<h2><b>Análisis de Entidades y Personajes Literarios mediante NLP en Obras Narrativas</b></h2>

<hr>

<table style="margin-left:auto; margin-right:auto;">
  <tr>
    <td><b>Alumno:</b></td>
    <td>López Llaja, Abel Ricardo</td>
  </tr>
  <tr>
    <td><b>Profesor:</b></td>
    <td>Mamani Bustamante, Juan Pablo</td>
  </tr>
  <tr>
    <td><b>Curso:</b></td>
    <td>Procesamiento del Lenguaje Natural</td>
  </tr>
  <tr>
    <td><b>Ciclo:</b></td>
    <td>V</td>
  </tr>
</table>

<hr>

<h3><b>CHACHAPOYAS – PERÚ</b></h3>
<h3><b>2026-I</b></h3>

</div>
""")

Alumno:,"López Llaja, Abel Ricardo"
Profesor:,"Mamani Bustamante, Juan Pablo"
Curso:,Procesamiento del Lenguaje Natural
Ciclo:,V

# 1. Introducción
En este notebook aplican técnicas de Procesamiento de Lenguaje Natural a dos obras literarias: **Conversación en La Catedral** de Mario Vargas Llosa y **Comentarios reales de los incas** del Inca Garcilaso de la Vega. El propósito es extraer entidades relevantes como personajes, lugares y escenarios, y posteriormente analizar relaciones entre personajes mediante redes de coocurrencia.

# 2. Objetivos del análisis
**Objetivo general:**

- Aplicar técnicas de NLP para extraer entidades literarias y analizar relaciones entre personajes en dos obras de la literatura peruana.

**Objetivos específicos:**
- Cargar y organizar los textos por unidad narrativa.
- Limpiar y segmentar los textos para su procesamiento.
- Extraer entidades nombradas usando Flair.
- Clasificar entidades en personajes, lugares y otras categorías.
- Construir redes de coocurrencia entre personajes.
- Calcular métricas de centralidad.
- Visualizar redes mediante PyVis.

# 3. Descripción del corpus

El corpus utilizado en este trabajo está compuesto por dos obras literarias peruanas en formato `.txt`:

| Código de obra | Título | Autor | Tipo de texto |
|---|---|---|---|
| CELC_MVLL | Conversación en La Catedral | Mario Vargas Llosa | Novela |
| CRDLI_IGDLV | Comentarios reales de los incas | Inca Garcilaso de la Vega | Crónica histórica |

Ambos textos fueron obtenidos previamente a partir de archivos de extensión `.epub` y convertidos a texto plano. Para simplificar el flujo de procesamiento, se trabajó con cada obra como un libro completo, en lugar de analizar sus divisiones internas por partes, libros o capítulos.

Los textos fueron cargados desde archivos alojados en [GitHub](https://github.com/elable947/proyecto_nlp_libros.git) mediante URLs en formato `raw`. Posteriormente, cada libro fue segmentado automáticamente en bloques de texto para facilitar el procesamiento con herramientas de NLP.

El análisis se centra en:

- Extracción de entidades nombradas.
- Identificación de personajes.
- Identificación de lugares y escenarios.
- Construcción de redes de coocurrencia entre personajes.
- Cálculo de métricas de centralidad.
- Visualización interactiva de relaciones mediante PyVis.

# 4. Importación de librerias

In [0]:
%pip install flair spacy networkx pyvis

Requirement already satisfied: flair in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (0.15.1)
Requirement already satisfied: spacy in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (3.8.14)
Requirement already satisfied: networkx in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (3.6.1)
Requirement already satisfied: pyvis in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (0.3.2)
Requirement already satisfied: boto3>=1.20.27 in /databricks/python3/lib/python3.12/site-packages (from flair) (1.40.45)
Requirement already satisfied: conllu<5.0.0,>=4.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (4.5.3)
Requirement already satisfied: deprecated>=1.2.13 in /databricks/python3/lib/python3.12/site-packages (from flair) (1.2.18)
Requirement already satisfied: ftfy>=6.1.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (6.3.1)
Requirement already satisfied: gdown>=4.4.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (6.0.0)
Requirement already satisfied: huggingface-hub>=0.10.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (0.36.2)
Requirement already satisfied: langdetect>=1.0.9 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (1.0.9)
Requirement already satisfied: lxml>=4.8.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (6.1.0)
Requirement already satisfied: matplotlib>=2.2.3 in /databricks/python3/lib/python3.12/site-packages (from flair) (3.10.0)
Requirement already satisfied: more-itertools>=8.13.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (11.0.2)
Requirement already satisfied: mpld3>=0.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (0.5.12)
Requirement already satisfied: pptree>=3.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /databricks/python3/lib/python3.12/site-packages (from flair) (2.9.0.post0)
Requirement already satisfied: pytorch-revgrad>=0.2.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (0.2.0)
Requirement already satisfied: regex>=2022.1.18 in /databricks/python3/lib/python3.12/site-packages (from flair) (2024.11.6)
Requirement already satisfied: scikit-learn>=1.0.2 in /databricks/python3/lib/python3.12/site-packages (from flair) (1.6.1)
Requirement already satisfied: segtok>=1.5.11 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (1.5.11)
Requirement already satisfied: sqlitedict>=2.0.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (2.1.0)
Requirement already satisfied: tabulate>=0.8.10 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (0.10.0)
Requirement already satisfied: torch>=1.13.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (2.11.0)
Requirement already satisfied: tqdm>=4.63.0 in /databricks/python3/lib/python3.12/site-packages (from flair) (4.67.1)
Requirement already satisfied: transformer-smaller-training-vocab>=0.2.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (0.4.2)
Requirement already satisfied: transformers<5.0.0,>=4.25.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from transformers[sentencepiece]<5.0.0,>=4.25.0->flair) (4.57.6)
Requirement already satisfied: wikipedia-api>=0.5.7 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (0.14.1)
Requirement already satisfied: bioc<3.0.0,>=2.0.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from flair) (2.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from spacy) (0.25.1)
Requirement already satisfied: numpy>=1.19.0 in /databricks/python3/lib/python3.12/site-packages (from spacy) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /databricks/python3/lib/python3.12/site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /databricks/python3/lib/python3.12/site-packages (from spacy) (2.10.6)
Requirement already satisfied: jinja2 in /databricks/python3/lib/python3.12/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (78.1.1)
Requirement already satisfied: packaging>=20.0 in /databricks/python3/lib/python3.12/site-packages (from spacy) (24.2)
Requirement already satisfied: ipython>=5.3.0 in /databricks/python3/lib/python3.12/site-packages (from pyvis) (8.30.0)
Requirement already satisfied: jsonpickle>=1.4.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from pyvis) (4.1.1)
Requirement already satisfied: jsonlines>=1.2.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from bioc<3.0.0,>=2.0.0->flair) (4.0.0)
Requirement already satisfied: intervaltree in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from bioc<3.0.0,>=2.0.0->flair) (3.2.1)
Requirement already satisfied: docopt in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from bioc<3.0.0,>=2.0.0->flair) (0.6.2)
Requirement already satisfied: botocore<1.41.0,>=1.40.45 in /databricks/python3/lib/python3.12/site-packages (from boto3>=1.20.27->flair) (1.40.45)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /databricks/python3/lib/python3.12/site-packages (from boto3>=1.20.27->flair) (1.0.1)
Requirement already satisfied: s3transfer<0.15.0,>=0.14.0 in /databricks/python3/lib/python3.12/site-packages (from boto3>=1.20.27->flair) (0.14.0)
Requirement already satisfied: wrapt<2,>=1.10 in /databricks/python3/lib/python3.12/site-packages (from deprecated>=1.2.13->flair) (1.17.0)
Requirement already satisfied: wcwidth in /databricks/python3/lib/python3.12/site-packages (from ftfy>=6.1.0->flair) (0.2.5)
Requirement already satisfied: beautifulsoup4 in /databricks/python3/lib/python3.12/site-packages (from gdown>=4.4.0->flair) (4.12.3)
Requirement already satisfied: filelock in /databricks/python3/lib/python3.12/site-packages (from gdown>=4.4.0->flair) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in /databricks/python3/lib/python3.12/site-packages (from huggingface-hub>=0.10.0->flair) (2023.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /databricks/python3/lib/python3.12/site-packages (from huggingface-hub>=0.10.0->flair) (1.2.0)
Requirement already satisfied: pyyaml>=5.1 in /databricks/python3/lib/python3.12/site-packages (from huggingface-hub>=0.10.0->flair) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /databricks/python3/lib/python3.12/site-packages (from huggingface-hub>=0.10.0->flair) (4.12.2)
Requirement already satisfied: decorator in /databricks/python3/lib/python3.12/site-packages (from ipython>=5.3.0->pyvis) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /databricks/python3/lib/python3.12/site-packages (from ipython>=5.3.0->pyvis) (0.19.2)
Requirement already satisfied: matplotlib-inline in /databricks/python3/lib/python3.12/site-packages (from ipython>=5.3.0->pyvis) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /databricks/python3/lib/python3.12/site-packages (from ipython>=5.3.0->pyvis) (4.8.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /databricks/python3/lib/python3.12/site-packages (from ipython>=5.3.0->pyvis) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /databricks/python3/lib/python3.12/site-packages (from ipython>=5.3.0->pyvis) (2.19.1)
Requirement already satisfied: stack_data in /databricks/python3/lib/python3.12/site-packages (from ipython>=5.3.0->pyvis) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /databricks/python3/lib/python3.12/site-packages (from ipython>=5.3.0->pyvis) (5.14.3)
Requirement already satisfied: MarkupSafe>=2.0 in /databricks/python3/lib/python3.12/site-packages (from jinja2->spacy) (3.0.2)
Requirement already satisfied: six in /databricks/python3/lib/python3.12/site-packages (from langdetect>=1.0.9->flair) (1.17.0)
Requirement already satisfied: contourpy>=1.0.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib>=2.2.3->flair) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /databricks/python3/lib/python3.12/site-packages (from matplotlib>=2.2.3->flair) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /databricks/python3/lib/python3.12/site-packages (from matplotlib>=2.2.3->flair) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib>=2.2.3->flair) (1.4.8)
Requirement already satisfied: pillow>=8 in /databricks/python3/lib/python3.12/site-packages (from matplotlib>=2.2.3->flair) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib>=2.2.3->flair) (3.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /databricks/python3/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /databricks/python3/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.27.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /databricks/python3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /databricks/python3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /databricks/python3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /databricks/python3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.4.26)
Requirement already satisfied: scipy>=1.6.0 in /databricks/python3/lib/python3.12/site-packages (from scikit-learn>=1.0.2->flair) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /databricks/python3/lib/python3.12/site-packages (from scikit-learn>=1.0.2->flair) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /databricks/python3/lib/python3.12/site-packages (from scikit-learn>=1.0.2->flair) (3.5.0)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: sympy>=1.13.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from torch>=1.13.1->flair) (1.14.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.1->flair) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from torch>=1.13.1->flair) (13.2.0)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from torch>=1.13.1->flair) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from torch>=1.13.1->flair) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from torch>=1.13.1->flair) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from torch>=1.13.1->flair) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from torch>=1.13.1->flair) (3.6.0)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.1->flair) (13.0.88)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.1->flair) (1.15.1.6)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.1->flair) (12.0.4.66)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.1->flair) (13.0.85)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.1->flair) (13.0.85)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.1->flair) (12.0.0.61)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.1->flair) (13.0.96)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.1->flair) (13.1.0.3)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.1->flair) (10.4.0.35)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.1->flair) (13.0.88)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.1->flair) (12.6.3.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /databricks/python3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.25.0->transformers[sentencepiece]<5.0.0,>=4.25.0->flair) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4ec6dd82-4168-432c-8b49-15b7c1980b45/lib/python3.12/site-packages (from transformers<5.0.0,>=4.25.0->transformers[sentencepiece]<5.0.0,>=4.25.0->flair) (0.7.0)

In [0]:
# Instalación del modelo pequeño de spaCy para español.
# Se instala desde el wheel oficial para asegurar compatibilidad con spaCy 3.8.
%pip install https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.8.0/es_core_news_sm-3.8.0-py3-none-any.whl

Collecting es-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.8.0/es_core_news_sm-3.8.0-py3-none-any.whl (12.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 110.2 MB/s eta 0:00:00
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
#dbutils.library.restartPython() # reiniciamos el kernel para poder usar las librerías instaladas

In [0]:
import os
import re
from pathlib import Path
from collections import Counter
from itertools import combinations

# Descarga y manipulación de datos
import requests
import pandas as pd

# Procesamiento de lenguaje natural
import spacy
from flair.data import Sentence
from flair.models import SequenceTagger

# Redes y visualización
import networkx as nx
from pyvis.network import Network
import matplotlib.pyplot as plt

# 5. Configuración de rutas y parámetros

In [0]:
URL_CELC = "https://raw.githubusercontent.com/elable947/proyecto_nlp_libros/refs/heads/main/data/txt/CELC_MVLL/CELC_MVLL_libro_completo.txt"

URL_CRDLI = "https://raw.githubusercontent.com/elable947/proyecto_nlp_libros/refs/heads/main/data/txt/CRDLI_IGDLV/CRDLI_IGDLV_libro_completo.txt"

# Parámetros principales del análisis.
MAX_PALABRAS_BLOQUE = 700      # Tamaño aproximado de cada bloque de texto.
UMBRAL_SCORE_NER = 0.80        # Umbral reservado para filtrar entidades si se desea mayor precisión.
MIN_PESO_RED = 2               # Peso mínimo para conservar una relación de coocurrencia.

OBRAS = {
    "CELC_MVLL": "Conversación en La Catedral",
    "CRDLI_IGDLV": "Comentarios reales de los incas"
}

RUTA_SALIDA = "/Volumes/workspace/default/mi_volumen/proyecto_nlp_libros" # para guardar resultados
RUTA_GRAFOS = f"{RUTA_SALIDA}/grafos"

# Se crean las carpetas de salida si el volumen ya existe.
Path(RUTA_SALIDA).mkdir(parents=True, exist_ok=True)
Path(RUTA_GRAFOS).mkdir(parents=True, exist_ok=True)

print("Ruta de salida configurada:", RUTA_SALIDA)
print("Ruta para grafos configurada:", RUTA_GRAFOS)

Ruta de salida configurada: /Volumes/workspace/default/mi_volumen/proyecto_nlp_libros
Ruta para grafos configurada: /Volumes/workspace/default/mi_volumen/proyecto_nlp_libros/grafos

# 6. Carga de libros completos

In [0]:
def cargar_texto_desde_url(url): # funcion para cargar los libros desde github
    response = requests.get(url)
    response.raise_for_status()
    return response.text

In [0]:
contenido_celc = cargar_texto_desde_url(URL_CELC)
contenido_crdli = cargar_texto_desde_url(URL_CRDLI)
print(contenido_celc[:500])

Conversación en La Catedral

Mario Vargas Llosa

UNO
I


Desde la puerta de
La Crónica
 Santiago mira la avenida Tacna, sin amor: automóviles, edificios desiguales y descoloridos, esqueletos de avisos luminosos flotando en la neblina, el mediodía gris. ¿En qué momento se había jodido el Perú? Los canillitas merodean entre los vehículos detenidos por el semáforo de Wilson voceando los diarios de la tarde y él echa a andar, despacio, hacia la Colmena. Las manos en los bolsillos, cabizbajo, va esco

In [0]:
print(contenido_crdli[:500])

Comentarios Reales de los Incas

Inca Garcilaso de la Vega

LIBRO PRIMERO


donde se trata el descubrimiento del Nuevo Mundo, la deducción del

 nombre Perú, la idolatría y manera de vivir antes de los Reyes Incas,

el origen de ellos, la vida del primer Inca y lo que hizo con sus

vasallos, y la significación de los nombres reales.


Contiene veinte y seis capítulos.

Capítulo I: Si hay muchos mundos. Trata de las cinco Zonas.


Habiendo de tratar del Nuevo Mundo, o de la mejor y más principal

In [0]:
df_textos = pd.DataFrame([
    {
        "obra": "CELC_MVLL",
        "titulo": "Conversación en La Catedral",
        "autor": "Mario Vargas Llosa",
        "texto": contenido_celc
    },
    {
        "obra": "CRDLI_IGDLV",
        "titulo": "Comentarios reales de los incas",
        "autor": "Inca Garcilaso de la Vega",
        "texto": contenido_crdli
    }
])

df_textos["num_caracteres"] = df_textos["texto"].str.len()
df_textos["num_palabras_aprox"] = df_textos["texto"].str.split().str.len()

display(df_textos[["obra", "titulo", "autor", "num_caracteres", "num_palabras_aprox"]])

obra,titulo,autor,num_caracteres,num_palabras_aprox
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1186153,208831
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,1513463,266275

# 7. Limpieza y normalización básica

Antes de aplicar NLP, se normalizan saltos de línea, espacios repetidos y caracteres invisibles. Esta limpieza no elimina puntuación ni tildes, porque esos elementos pueden ayudar al reconocimiento de entidades y a conservar mejor el contexto literario.

In [0]:
def limpiar_texto(texto):
    texto = texto.replace("\ufeff", "")
    texto = texto.replace("\r\n", "\n")
    texto = texto.replace("\r", "\n")
    texto = re.sub(r"\n{3,}", "\n\n", texto)
    texto = re.sub(r"[ \t]+", " ", texto)
    texto = texto.strip()
    return texto

df_textos["texto_limpio"] = df_textos["texto"].apply(limpiar_texto)

# 8. Segmentación automática en bloques

Los modelos de NLP pueden ser costosos cuando se aplican sobre libros completos. Por eso, cada obra se divide en bloques de tamaño controlado. Cada bloque mantiene metadatos de obra, título, autor e identificador numérico.

En este trabajo, el bloque funciona como unidad de análisis: las entidades se extraen por bloque y las coocurrencias entre personajes se calculan cuando aparecen dentro del mismo bloque.

In [0]:
def dividir_en_bloques(texto, max_palabras=700):
    parrafos = [p.strip() for p in texto.split("\n\n") if p.strip()]
    
    bloques = []
    bloque_actual = []
    palabras_actuales = 0

    for parrafo in parrafos:
        palabras = parrafo.split()
        n_palabras = len(palabras)

        if palabras_actuales + n_palabras > max_palabras and bloque_actual:
            bloques.append("\n\n".join(bloque_actual))
            bloque_actual = []
            palabras_actuales = 0

        bloque_actual.append(parrafo)
        palabras_actuales += n_palabras

    if bloque_actual:
        bloques.append("\n\n".join(bloque_actual))

    return bloques

In [0]:
registros_bloques = []

for _, row in df_textos.iterrows():
    bloques = dividir_en_bloques(
        row["texto_limpio"],
        max_palabras=MAX_PALABRAS_BLOQUE
    )

    for i, bloque in enumerate(bloques, start=1):
        registros_bloques.append({
            "obra": row["obra"],
            "titulo": row["titulo"],
            "autor": row["autor"],
            "bloque_id": i,
            "texto_bloque": bloque,
            "num_palabras_bloque": len(bloque.split())
        })

df_bloques = pd.DataFrame(registros_bloques)

display(df_bloques.head())

In [0]:
display(df_bloques[333:].head())

obra,titulo,autor,bloque_id,texto_bloque,num_palabras_bloque
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,1,"Comentarios Reales de los Incas Inca Garcilaso de la Vega LIBRO PRIMERO donde se trata el descubrimiento del Nuevo Mundo, la deducción del nombre Perú, la idolatría y manera de vivir antes de los Reyes Incas, el origen de ellos, la vida del primer Inca y lo que hizo con sus vasallos, y la significación de los nombres reales. Contiene veinte y seis capítulos. Capítulo I: Si hay muchos mundos. Trata de las cinco Zonas. Habiendo de tratar del Nuevo Mundo, o de la mejor y más principal parte suya, que son los reinos y provincias del Imperio llamado Perú, de cuyas antiguallas y origen de sus Reyes pretendemos escribir, parece que fuera justo, conforme a la común costumbre de los escritores, tratar aquí al principio si el mundo es uno sólo o si hay muchos mundos; si es llano o redondo, y si también lo es el cielo redondo o llano; si es habitable toda la tierra o no más de las zonas templadas; si hay paso de una templada a la otra; si hay antípodas y cuáles son de cuáles, y otras cosas semejantes que los antiguos filósofos muy larga y curiosamente trataron y los modernos no dejan de platicar y escribir, siguiendo cada cual opinión que más le agrada. Mas porque no es aqueste mi principal intento ni las fuerzas de un indio pueden presumir tanto, y también porque la experiencia, después que se descubrió lo que llaman Nuevo Mundo, nos ha desengañado de la mayor parte de estas dudas, pasaremos brevemente por ellas, por ir a otra parte, a cuyos términos finales temo no llegar. Mas confiado en la infinita misericordia, digo que a lo primero se podrá afirmar que no hay más que un mundo, y aunque llamarnos Mundo Viejo y Mundo Nuevo, es por haberse descubierto aquél nuevamente para nosotros, y no porque sean dos, sino todo uno. Y a los que todavía imaginaren que hay muchos mundos, no hay para qué responderles, sino que se estén en sus heréticas imaginaciones hasta que en el infierno se desengañen de ellas. Y a los que dudan, si hay alguno que lo dude, si es llano o redondo se podrá satisfacer con el testimonio de los que han dado vuelta a todo él o a la mayor parte, como los de la nao Victoria y otros que después acá le han rodeado. Y a lo del cielo, si también es llano o redondo, se podrá responder con las palabras del Real Profeta: Extendens c&lum, sicut pellem en las cuales nos quiso mostrar la forma y hechura de la obra, dando la una por ejemplo de la otra, diciendo: «Que extendiste el cielo así como la piel», esto es, cubriendo con el cielo este gran cuerpo de los cuatro elementos en redondo, así como cubriste con la piel en redondo el cuerpo del animal, no solamente lo principal de él, mas también todas sus partes, por pequeñas que sean. A los que afirman que de las cinco partes del mundo que llaman zonas no son habitables más de las dos templadas, y que la del medio por su [e]xcesivo calor y las dos de los cabos por el demasiado frío son inhabitables, y que de la una zona habitable no se puede pasar a la otra habitable por el calor demasiado que hay en medio, puedo afirmar, demás de lo que todos saben, que yo nací en la tórrida zona, que es en el Cozco, y me crié en ella hasta los veinte años, y he estado en la otra zona templada de la otra parte del Trópico de Capricornio, a la parte del sur, en los últimos términos de los Charcas, que son los Chichas, y, para venir a esta otra templada de la parte del norte, donde escribo esto, pasé por la tórrida zona y la atravesé toda y estuve tres días naturales debajo de la línea equinoccial, donde dicen que pasa perpendicularmente, que es en el cabo de Pasau por todo lo cual digo que es habitable la tórrida también como las templadas. De las zonas frías quisiera poder decir por vista de ojos como de las otras tres. Remítame a",697
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,2,"los que saben de ellas más que yo. A los que dicen que por su mucha frialdad son inhabitables, osaré decir, con los que tienen lo contrario, que también son habitables como las demás, porque en buena consideración no es de imaginar, cuanto más de creer, que partes tan grandes del mundo las hiciese Dios inútiles, habiéndolo criado todo para que lo habitasen los hombres, y que se engañan los antiguos en lo que dicen de las zonas frías, también como se engañaron en lo que dijeron de la tórrida, que era inhabitable por su mucho calor. Antes se debe creer que el Señor, como padre sabio y poderoso, y la naturaleza, como madre universal y piadosa, hubiesen remediado los inconvenientes de la frialdad con templanza de calor, como remediaron el demasiado calor de la tórrida zona con tantas nieves, fuentes, ríos y lagos como en el Perú se hallan, que la hacen templada de tanta variedad de temples: unas que declinan a calor y a más calor, hasta llegar a regiones tan bajas, y por ende tan calientes, que, por su mucho calor, son casi inhabitables, como dijeron los antiguos de ella; otras regiones, que declinan a frío y más frío, hasta subir a partes tan altas que también llegan a ser inhabitables por la mucha frialdad de la nieve perpetua que sobre sí tienen, en contra de lo que de esta tórrida zona los filósofos dijeron, que no imaginaron jamás que en ella pudiese haber nieve, habiéndola perpetua debajo de la misma línea equinoccial, sin menguar jamás ni mucho ni poco, a lo menos en la cordillera grande, si no es en las faldas o puertos de ella. Y es de saber que en la tórrida zona, en lo que de ella alcanza el Perú, no consiste el calor ni el frío en distancia de regiones, ni en estar más lejos ni más cerca de la equinoccial, sino en estar más alto o más bajo de una misma región y en muy poca distancia de tierra, como adelante se dirá más largo. Digo, pues, que a esta semejanza se puede creer que también las zonas frías estén templadas y sean habitables, como lo tienen muchos graves autores, aunque no por vista y experiencia; pero basta haberlo dado a entender así el mismo Dios, cuando crió al hombre y le dijo: «creced y multiplicad y henchid la tierra y sojuzgadla». Por donde se ve que es habitable, porque, si no lo fuera, ni se podía sojuzgar ni llenar de habitaciones. Yo espero en su omnipotencia que a su tiempo descubriera estos secretos (como descubrió el Nuevo Mundo) para mayor confusión y afrenta de los atrevidos, que con sus filosofías naturales y entendimientos humanos quieren tasar la potencia y la sabiduría de Dios, que no pueda hacer sus obras más de como ellos las imaginan, habiendo tanta disparidad del un saber al otro cuanta hay de lo finito a lo infinito. Etc. Capítulo II: Si hay antípodas. A lo que se dice si hay antípodas o no, se podrá decir que, siendo el mundo redondo (como es notorio), cierto es que las hay. Empero tengo para mí que por no estar este mundo inferior descubierto del todo, no se puede saber de cierto cuáles provincias sean antípodas de cuáles, como algunos lo afirman, lo cual se podrá certificar más aína respecto del cielo que no de la tierra, como los polos el uno del otro y el oriente del poniente, dondequiera que lo es por la equinoccial. Por dónde hayan pasado aquellas gentes tantas y de tan diversas lenguas y costumbres como las que en el Nuevo Mundo se han hallado, tampoco se sabe de cierto, porque si dicen por la mar, en navíos, nacen inconvenientes acerca de los animales que allá se hallan, sobre decir cómo o para qué los embarcaron, siendo algunos de ellos antes dañosos que provechosos. Pues decir que pudieron ir por tierra, también nacen otros inconvenientes mayores, como es decir que si llevaron los animales que allá tenían domésticos, ¿por qué no llevaron de los que acá quedaron, que se han llevado después [de] acá? Y si fue por no poder",696
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,3,"llevar tantos ¿cómo no quedaron acá de los que llevaron? Y lo mismo se puede decir de las mieses, legumbres y frutas, tan diferentes de las de acá, que con razón le llamaron Nuevo Mundo, porque lo es en toda cosa, así en los animales mansos y bravos como en las comidas, como en los hombres, que generalmente son lampiños, sin barbas. Y porque en cosas tan inciertas es perdido el trabajo que se gasta en quererlas saber, las dejaré, porque tengo menos suficiencia que otro para inquirirlas. Solamente trataré del origen de los Reyes Incas y de la sucesión de ellos, sus conquistas, leyes y gobierno en paz y en guerra. Y antes que tratemos de ellos será bien digamos cómo se descubrió este Nuevo Mundo, y luego trataremos del Perú en particular. Capítulo III: Cómo se descubrió el Nuevo Mundo. Cerca del año de mil y cuatrocientos y ochenta y cuatro, uno más o menos, un piloto natural de la villa de Huelva, en el Condado de Niebla, llamado Alonso Sánchez de Huelva, tenía un navío pequeño, con el cual contrataba por la mar, y llevaba de España a las Canarias algunas mercaderías que allí se le vendían bien, y de las Canarias cargaba de los frutos de aquellas islas y las llevaba a la isla de la Madera y de allí se volvía a España cargado de azúcar y conservas. Andando en esta su triangular contratación, atravesando de las Canarias a la isla de la Madera, le dio un temporal tan recio y tempestuoso que, no pudiendo resistirle, se dejó llevar de la tormenta y corrió veinte y ocho o veinte y nueve días sin saber por dónde ni adónde, porque en todo este tiempo no pudo tomar el altura por el sol ni por el norte. Padecieron los del navío grandísimo trabajo en la tormenta, porque ni les dejaba comer ni dormir. Al cabo de este largo tiempo se aplacó el viento y se hallaron cerca de una isla; no se sabe de cierto cuál fue, mas de que se sospecha que fue la que ahora llaman Santo Domingo; y es de mucha consideración que el viento que con tanta violencia y tormenta llevó aquel navío no pudo ser otro sino el solano, que llaman leste, porque la isla de Santo Domingo está al poniente de las Canarias, el cual viento, en aquel viaje, antes aplaca las tormentas que las levanta. Mas el Señor Todopoderoso, cuando quiere hacer misericordias, saca las más misteriosas y necesarias de causas contrarias, como sacó el agua del pedernal y la vista del ciego del lodo que le puso en los ojos, para que notoriamente se muestren ser obras de la miseración y bondad divina, que también usó de esta su piedad para enviar su Evangelio y luz verdadera a todo el Nuevo Mundo, que tanta necesidad tenía de ella, pues vivían, o, por mejor decir, perecían en las tinieblas de la gentilidad e idolatría tan bárbara y bestial como en el discurso de la historia veremos. El piloto saltó en tierra, tomó el altura y escribió por menudo todo lo que vio y lo que le sucedió por la mar a ida y a vuelta, y, habiendo tomado agua y leña, se volvió a tiento, sin saber el viaje tampoco a la venida como a la ida, por lo cual gastó más tiempo del que le convenía. Y por la dilación del camino les faltó el agua y el bastimento, de cuya causa, y por el mucho trabajo que a ida y venida habían padecido, empezaron a enfermar y morir de tal manera que de diez y siete hombres que salieron de España no llegaron a la Tercera más de cinco, y entre ellos el piloto Alonso Sánchez de Huelva. Fueron a parar a casa del famoso Cristóbal Colón, genovés, porque supieron que era gran piloto y cosmógrafo y que hacía cartas de marear, el cual los recibió con mucho amor y les hizo todo regalo por saber cosas acaecidas en tan extraño y largo naufragio como el que decían haber padecido. Y como llegaron tan descaecidos del trabajo pasado, por mucho que Cristóbal",694
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,4,"Colón les regaló no pudieron volver en sí y murieron todos en su casa, dejándole en herencia los trabajos que les causaron la muerte, los cuales aceptó el gran Colón con tanto ánimo y esfuerzo que, habiendo sufrido otros tan grandes y aun mayores (pues duraron más tiempo), salió con la empresa de dar el Nuevo Mundo y sus riquezas a España, como lo puso por blasón en sus armas diciendo: «A Castilla y a León, Nuevo Mundo dio Colón». Quien quisiere ver las grandes hazañas de este varón, vea la Historia general de las Indias que Francisco López de Gómara escribió, que allí las hallará, aunque abreviadas, pero lo que más loa y engrandece a este famoso sobre los famosos es la misma obra de esta conquista y descubrimiento. Yo quise añadir esto poco que faltó de la relación de aquel antiguo historiador, que, como escribió lejos de donde acaecieron estas cosas y la relación se la daban yentes y vinientes, le dijeron muchas cosas de las que pasaron, pero imperfectas, y yo las oí en mi tierra a mi padre y a sus contemporáneos, que en aquellos tiempos la mayor y más ordinaria conversación que tenían era repetir las cosas más hazañosas y notables que en sus conquistas habían acaecido, donde contaban la que hemos dicho y otras que adelante diremos, que, como alcanzaron a mucho[s] de los primeros descubridores y conquistadores del Nuevo Mundo, hubieron de ellos la entera relación de semejantes cosas, y yo, como digo, las oí a mis mayores, aunque (como muchacho) con poca atención, que si entonces la tuviera pudiera ahora escribir otras muchas cosas de grande admiración, necesarias en esta historia. Diré las que hubiere guardado la memoria, con dolor de las que ha perdido. El muy reverendo Padre Joseph de Acosta toca también esta historia del descubrimiento del Nuevo Mundo con pena de no poderla dar entera, que también faltó a Su Paternidad parte de la relación en este paso, como en otros más modernos, porque se habían acabado ya los conquistadores antiguos cuando Su Paternidad pasó a aquellas partes, sobre lo cual dice estas palabras, Libro primero, capítulo diez y nueve: «Habiendo mostrado que no lleva camino pensar que los primeros moradores de Indias hayan venido a ellas con navegación hecha para ese fin, bien se sigue que si vinieron por mar haya sido acaso y por fuerza de tormentas el haber llegado a Indias, lo cual, por inmenso que sea el Mar Océano, no es cosa increíble. Porque pues así sucedió en el descubrimiento de nuestros tiempos cuando aquel marinero (cuyo nombre aún no sabemos, para que negocio tan grande no se atribuya a otro autor sino a Dios), habiendo por un terrible e importuno temporal reconocido el Nuevo Mundo, dejó por paga del buen hospedaje a Cristóbal Colón la noticia de cosa tan grande. Así puso ser», etc. Hasta aquí es del Padre Maestro Acosta, sacado a la letra, donde muestra haber hallado Su Paternidad en el Perú parte de nuestra relación, y aunque no toda, pero lo más esencial de ella. Este fue el primer principio y origen del descubrimiento del Nuevo Mundo, de la cual grandeza podía loarse la pequeña villa de Huelva, que tal hijo crió, de cuya relación, certificado Cristóbal Colón, insistió tanto en su demanda, prometiendo cosas nunca vistas ni oídas, guardando como hombre prudente el secreto de ellas, aunque debajo de confianza dio cuenta de ellas a algunas personas de mucha autoridad cerca de los Reyes Católicos, que te ayudaron a salir con su empresa, que si no fuera por esta noticia que Alonso Sánchez de Huelva le dio, no pudiera de sola su imaginación de cosmografía prometer tanto y tan certificado como prometió ni salir tan presto con la empresa del descubrimiento, pues, según aquel autor, no tardó Colón más de sesenta y ocho días en el viaje hasta la isla de Guanatianico, con detenerse algunos días en la Gomera a tomar refresco que, si no supiera por la relación de Alonso Sánchez qué rumbos había de tomar en un mar tan grande, era casi milagro haber ido allá en tan breve tiempo. Capítulo IV: La deducción del nombre Perú.",699
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,5,"Pues hemos de tratar del Perú, será bien digamos aquí cómo se dedujo este nombre, no lo teniendo los indios en su lenguaje; para lo cual es de saber que, habiendo descubierto la Mar del Sur Vasco Núñez de Balboa, caballero natural de Jerez de Badajoz, año de mil y quinientos y trece, que fue el primer español que la descubrió y vio, y habiéndole dado los Reyes Católicos título de Adelantado de aquella mar con la conquista y gobierno de los reinos que por ella descubriese, en los pocos años que después de esta merced vivió (hasta que su propio suegro, el gobernador Pedro Arias de Ávila, en lugar de muchas mercedes que había merecido y se le debían por sus hazañas, le cortó la cabeza), tuvo este caballero cuidado de descubrir y saber qué tierra era y cómo se llamaba la que corre de Panamá adelante hacia el sur. Para este efecto hizo tres o cuatro navíos, los cuales, mientras él aderezaba las cosas necesarias para su descubrimiento y conquista, enviaba cada uno de por sí en diversos tiempos del año a descubrir aquella costa. Los navíos, habiendo hecho las diligencias que podían, volvían con la relación de muchas tierras que hay por aquella ribera. Un navío de éstos subió más que los otros y pasó la línea equinoccial a la parte del sur, y cerca de ella, navegando costa a costa, como se navegaba entonces por aquel viaje, vio un indio que a la boca de un río, de muchos que por toda aquella tierra entran en la mar, estaba pescando. Los españoles del navío, con todo el recato posible, echaron en tierra, lejos de donde el indio estaba, cuatro españoles, grandes corredores y nadadores, para que no se les fuese por tierra ni por agua. Hecha esta diligencia, pasaron con el navío por delante del indio, para que pusiese ojos en él y se descuidase de la celada que le dejaban armada. El indio, viendo en la mar una cosa tan extraña, nunca jamás vista en aquella costa, como era navegar un navío a todas velas, se admiró grandemente y quedó pasmado y abobado, imaginando qué pudiese ser aquello que en la mar veía delante de sí. Y tanto se embebeció y enajenó en este pensamiento, que primero lo tuvieron abrazado los que le iban a prender que él los sintiese llegar, y así lo llevaron al navío con mucha fiesta y regocijo de todos ellos. Los españoles, habiéndole acariciado porque perdiese el miedo que de verlos con barbas y en diferente traje que el suyo había cobrado, le preguntaron por señas y por palabras qué tierra era aquélla y cómo se llamaba. El indio, por los ademanes y meneas que con manos y rostro le hacían (como a un mudo), entendía que le preguntaban mas no entendía lo que le preguntaban y a lo que entendió qué era el preguntarle, respondió a prisa (antes que le hiciesen algún mal) y nombró su propio nombre, diciendo Berú, y añadió otro y dijo Pelú. Quiso decir: «Si me preguntáis cómo me llamo, yo me digo Berú, y si me preguntáis dónde estaba, digo que estaba en el río». Porque es de saber que el nombre Pelú en el lenguaje de aquella provincia es nombre apelativo y significa río en común, como luego veremos en un autor grave. A otra semejante pregunta respondió el indio de nuestra historia de La Florida con el nombre de su amo, diciendo Brezos y Bredos (Libro sexto, capítulo quince), donde yo había puesto este paso a propósito del otro; de allí lo quité por ponerlo ahora en su lugar. Los cristianos entendieron conforme a su deseo, imaginando que el indio les había entendido y respondido a propósito, como si él y ellos hubieran hablado en castellano, y desde aquel tiempo, que fue el año de mil y quinientos y quince o diez y seis, llamaron Perú aquel riquísimo y grande Imperio, corrompiendo ambos nombres, como corrompen los españoles casi todos los vocablos que toman del lenguaje de los indios",677

In [0]:
display(
    df_bloques.groupby("obra").agg(
        cantidad_bloques=("bloque_id", "count"),
        promedio_palabras=("num_palabras_bloque", "mean"),
        min_palabras=("num_palabras_bloque", "min"),
        max_palabras=("num_palabras_bloque", "max")
    ).reset_index()
)

obra,cantidad_bloques,promedio_palabras,min_palabras,max_palabras
CELC_MVLL,333,627.1201201201201,1,1035
CRDLI_IGDLV,384,693.4244791666666,599,700

Aunque se definió un máximo de `700` palabras por bloque, este valor funciona como un límite aproximado. 
La función prioriza no cortar párrafos completos; por ello, si un párrafo individual supera las 700 palabras, 
ese párrafo se conserva como un solo bloque. Esto explica que el máximo observado pueda ser mayor al límite configurado.

El mínimo `1` probablemente viene de un párrafo muy corto, como un título, número de capítulo, separador o texto suelto.

# 9. Procesamiento lingüístico auxiliar con spaCy
Se carga el modelo en español de spaCy. En este notebook, spaCy se utiliza como apoyo lingüístico para tokenización y estructura del texto, mientras que la extracción principal de entidades se realiza con Flair.

Entonces con spaCy:
- tokenización
- segmentación
- limpieza lingüística
- detección de oraciones
- posible lematización
- posible análisis gramatical

La opción `disable=["ner"]` evita ejecutar el NER de spaCy y reduce el costo de procesamiento, ya que el reconocimiento de entidades se hará en la siguiente sección con Flair.

In [0]:
nlp = spacy.load("es_core_news_sm")

In [0]:
docs_spacy = []

for doc in nlp.pipe(
    df_bloques["texto_bloque"],
    batch_size=16, # lo podemos cambiar por 8
    disable=["ner"]
):
    docs_spacy.append(doc)

df_bloques["doc_spacy"] = docs_spacy

In [0]:
df_bloques.head(10)

        obra  ...                                          doc_spacy
0  CELC_MVLL  ...  (Conversación, en, La, Catedral, \n\n, Mario, ...
1  CELC_MVLL  ...  (—, ¿, Hasta, cuándo, va, a, seguir, la, campa...
2  CELC_MVLL  ...  (Todavía, hay, embotellamientos, en, el, centr...
3  CELC_MVLL  ...  (Almuerzan, sin, hablar, ,, en, la, mesita, pe...
4  CELC_MVLL  ...  (Que, no, se, pusiera, así, ,, amigo, periodis...
5  CELC_MVLL  ...  (No, era, él, ,, todos, los, negros, se, parec...
6  CELC_MVLL  ...  (¿, Y, la, niña, Teté, ?, ,, y, las, manazas, ...
7  CELC_MVLL  ...  (Huele, a, sudor, ,, ají, y, cebolla, ,, a, or...
8  CELC_MVLL  ...  (—, Menos, mal, que, le, alcanzó, la, plata, ,...
9  CELC_MVLL  ...  (—, Ya, está, —, solloza, Santiago, ,, incliná...

[10 rows x 7 columns]

In [0]:
df_bloques[333:].head(10)

            obra  ...                                          doc_spacy
333  CRDLI_IGDLV  ...  (Comentarios, Reales, de, los, Incas, \n\n, In...
334  CRDLI_IGDLV  ...  (los, que, saben, de, ellas, más, que, yo, ., ...
335  CRDLI_IGDLV  ...  (llevar, tantos, ¿, cómo, no, quedaron, acá, d...
336  CRDLI_IGDLV  ...  (Colón, les, regaló, no, pudieron, volver, en,...
337  CRDLI_IGDLV  ...  (Pues, hemos, de, tratar, del, Perú, ,, será, ...
338  CRDLI_IGDLV  ...  (de, aquella, tierra, ,, por, que, si, tomaron...
339  CRDLI_IGDLV  ...  (los, naturales, Pirú, ,, intitularon, toda, e...
340  CRDLI_IGDLV  ...  (tan, destrozados, que, falta, lo, más, y, mej...
341  CRDLI_IGDLV  ...  (aquella, tierra, que, corre, desde, la, equin...
342  CRDLI_IGDLV  ...  (La, isla, que, ha, por, nombre, la, Trinidad,...

[10 rows x 7 columns]

In [0]:
doc_ejemplo = df_bloques.loc[0, "doc_spacy"]

analisis_tokens = []

for token in doc_ejemplo[:30]:
    analisis_tokens.append({
        "token": token.text,
        "lema": token.lemma_,
        "categoria_gramatical": token.pos_,
        "dependencia": token.dep_,
        "es_stopword": token.is_stop,
        "es_puntuacion": token.is_punct
    })

df_analisis_spacy = pd.DataFrame(analisis_tokens)

display(df_analisis_spacy)

token,lema,categoria_gramatical,dependencia,es_stopword,es_puntuacion
Conversación,Conversación,PROPN,nsubj,false,false
en,en,ADP,case,true,false
La,el,DET,det,true,false
Catedral,Catedral,PROPN,nmod,false,false
,,SPACE,dep,false,false
Mario,Mario,PROPN,flat,false,false
Vargas,Vargas,PROPN,flat,false,false
Llosa,Llosa,PROPN,flat,false,false
,,SPACE,dep,false,false
UNO,UNO,PROPN,flat,true,false
,,SPACE,dep,false,false
I,I,CCONJ,flat,false,false
,,SPACE,dep,false,false
Desde,Desde,ADP,case,true,false
la,el,DET,det,true,false
puerta,puerta,NOUN,nmod,false,false
de,de,ADP,case,true,false
,,SPACE,dep,false,false
La,el,DET,det,true,false
Crónica,Crónica,PROPN,nmod,false,false
,,SPACE,dep,false,false
Santiago,Santiago,PROPN,flat,false,false
mira,mirar,VERB,ROOT,false,false
la,el,DET,det,true,false
avenida,avenida,NOUN,obj,false,false
Tacna,Tacna,PROPN,appos,false,false
",",",",PUNCT,punct,false,true
sin,sin,ADP,case,true,false
amor,amor,NOUN,nmod,false,false
:,:,PUNCT,punct,false,true

Para entender que significa cada etiqueta de la columna `categoria_gramatical` revisar la documentación de spaCy sobre [Part-of-Speech Tagging](https://spacy.io/usage/linguistic-features#pos-tagging) o [Universal POS tags](https://universaldependencies.org/u/pos/)

In [0]:
# Ejemplo de detección de oraciones con spaCy
oraciones = []

for i, sent in enumerate(doc_ejemplo.sents, start=1):
    oraciones.append({
        "oracion_id": i,
        "oracion": sent.text,
        "num_tokens": len(sent)
    })

df_oraciones_ejemplo = pd.DataFrame(oraciones)

display(df_oraciones_ejemplo.head(10))

oracion_id,oracion,num_tokens
1,"Conversación en La Catedral Mario Vargas Llosa UNO I Desde la puerta de La Crónica Santiago mira la avenida Tacna, sin amor: automóviles, edificios desiguales y descoloridos, esqueletos de avisos luminosos flotando en la neblina, el mediodía gris.",50
2,¿En qué momento se había jodido el Perú?,10
3,"Los canillitas merodean entre los vehículos detenidos por el semáforo de Wilson voceando los diarios de la tarde y él echa a andar, despacio, hacia la Colmena.",30
4,"Las manos en los bolsillos, cabizbajo, va escoltado por transeúntes que avanzan, también, hacia la Plaza San Martín.",23
5,"El era como el Perú, Zavalita, se había jodido en algún momento.",15
6,Piensa: ¿en cuál?,6
7,"Frente al Hotel Crillón un perro viene a lamerle los pies: no vayas a estar rabioso, fuera de aquí.",22
8,"El Perú jodido, piensa, Carlitos jodido, todos jodidos.",12
9,Piensa: no hay solución.,6
10,"Ve una larga cola en el paradero de los colectivos a Miraflores, cruza la Plaza y ahí está Norwin, hola hermano, en una mesa del Bar Zela, siéntate Zavalita, manoseando un chilcano y haciéndose lustrar los zapatos, le invitaba un trago.",48

In [0]:
def obtener_metricas_spacy(doc):
    tokens = [token for token in doc if not token.is_space]
    tokens_alpha = [token for token in tokens if token.is_alpha]
    oraciones = list(doc.sents)

    return {
        "num_tokens_spacy": len(tokens),
        "num_tokens_alpha": len(tokens_alpha),
        "num_oraciones": len(oraciones)
    }

metricas_spacy = df_bloques["doc_spacy"].apply(obtener_metricas_spacy)

df_metricas_spacy = pd.DataFrame(metricas_spacy.tolist())

df_bloques = pd.concat(
    [df_bloques.reset_index(drop=True), df_metricas_spacy],
    axis=1
)

display(df_bloques[[
    "obra",
    "bloque_id",
    "num_palabras_bloque",
    "num_tokens_spacy",
    "num_tokens_alpha",
    "num_oraciones"
]].head())

obra,bloque_id,num_palabras_bloque,num_tokens_spacy,num_tokens_alpha,num_oraciones
CELC_MVLL,1,688,853,677,53
CELC_MVLL,2,241,297,236,18
CELC_MVLL,3,693,859,684,53
CELC_MVLL,4,555,659,548,29
CELC_MVLL,5,698,870,689,50

In [0]:
display(df_bloques[[
    "obra",
    "bloque_id",
    "num_palabras_bloque",
    "num_tokens_spacy",
    "num_tokens_alpha",
    "num_oraciones"
]][333:].head())

obra,bloque_id,num_palabras_bloque,num_tokens_spacy,num_tokens_alpha,num_oraciones
CRDLI_IGDLV,1,697,777,695,13
CRDLI_IGDLV,2,696,789,696,14
CRDLI_IGDLV,3,694,769,694,15
CRDLI_IGDLV,4,699,784,697,10
CRDLI_IGDLV,5,677,762,677,14

# 10. Extracción de entidades nombradas con Flair

[Flair](https://github.com/flairNLP/flair.git) se utiliza para detectar entidades nombradas en español. Cada entidad extraída incluye el texto detectado, el tipo de entidad y un score de confianza.

Los tipos más relevantes para el análisis son:

- `PER`: personas, personajes o figuras mencionadas.
- `LOC`: lugares, espacios o referencias geográficas.
- `ORG`: organizaciones o instituciones.
- `MISC`: otras entidades diversas.

El resultado de esta sección será `df_entidades`, una tabla larga donde cada fila representa una entidad detectada en un bloque específico.

In [0]:
tagger = SequenceTagger.load("flair/ner-spanish-large")

pytorch_model.bin:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/616 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

2026-05-07 17:16:41,526 SequenceTagger predicts: Dictionary with 20 tags: <unk>, O, S-LOC, S-ORG, B-PER, I-PER, E-PER, S-MISC, B-ORG, E-ORG, S-PER, I-ORG, B-LOC, E-LOC, B-MISC, E-MISC, I-MISC, I-LOC, <START>, <STOP>

In [0]:
def extraer_entidades_flair(texto):
    sentence = Sentence(texto)
    tagger.predict(sentence)

    entidades = []

    for ent in sentence.get_spans("ner"):
        entidades.append({
            "entidad": ent.text,
            "tipo": ent.tag,
            "score": ent.score
        })

    return entidades

In [0]:
registros_entidades = []

for i, row in df_bloques.iterrows():
    entidades = extraer_entidades_flair(row["texto_bloque"])

    for ent in entidades:
        registros_entidades.append({
            "obra": row["obra"],
            "titulo": row["titulo"],
            "autor": row["autor"],
            "bloque_id": row["bloque_id"],
            "entidad": ent["entidad"],
            "tipo": ent["tipo"],
            "score": ent["score"]
        })

    if (i + 1) % 20 == 0:
        print(f"Bloques procesados: {i + 1}/{len(df_bloques)}")

df_entidades = pd.DataFrame(registros_entidades)

display(df_entidades.head())

Bloques procesados: 20/717
Bloques procesados: 40/717
Bloques procesados: 60/717
Bloques procesados: 80/717
Bloques procesados: 100/717
Bloques procesados: 120/717
Bloques procesados: 140/717
Bloques procesados: 160/717
Bloques procesados: 180/717
Bloques procesados: 200/717
Bloques procesados: 220/717
Bloques procesados: 240/717
Bloques procesados: 260/717
Bloques procesados: 280/717
Bloques procesados: 300/717
Bloques procesados: 320/717
Bloques procesados: 340/717
Bloques procesados: 360/717
Bloques procesados: 380/717
Bloques procesados: 400/717
Bloques procesados: 420/717
Bloques procesados: 440/717
Bloques procesados: 460/717
Bloques procesados: 480/717
Bloques procesados: 500/717
Bloques procesados: 520/717
Bloques procesados: 540/717
Bloques procesados: 560/717
Bloques procesados: 580/717
Bloques procesados: 600/717
Bloques procesados: 620/717
Bloques procesados: 640/717
Bloques procesados: 660/717
Bloques procesados: 680/717
Bloques procesados: 700/717

obra,titulo,autor,bloque_id,entidad,tipo,score
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,La Catedral,LOC,0.9997674822807312
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Mario Vargas Llosa,PER,0.9998625914255778
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,La Crónica,LOC,0.9999179244041443
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Santiago,PER,0.998166024684906
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,avenida Tacna,LOC,0.9997281134128571

In [0]:
df_entidades.sort_values('score', ascending=False).head(10)

              obra                           titulo  ... tipo     score
18542  CRDLI_IGDLV  Comentarios reales de los incas  ...  LOC  0.999989
20663  CRDLI_IGDLV  Comentarios reales de los incas  ...  LOC  0.999989
20664  CRDLI_IGDLV  Comentarios reales de los incas  ...  LOC  0.999987
20722  CRDLI_IGDLV  Comentarios reales de los incas  ...  LOC  0.999987
7819     CELC_MVLL      Conversación en La Catedral  ...  LOC  0.999987
20353  CRDLI_IGDLV  Comentarios reales de los incas  ...  LOC  0.999987
3877     CELC_MVLL      Conversación en La Catedral  ...  LOC  0.999987
20822  CRDLI_IGDLV  Comentarios reales de los incas  ...  LOC  0.999986
19939  CRDLI_IGDLV  Comentarios reales de los incas  ...  LOC  0.999986
18362  CRDLI_IGDLV  Comentarios reales de los incas  ...  LOC  0.999986

[10 rows x 7 columns]

In [0]:
df_entidades.sort_values('score', ascending=True).head(10)

              obra                           titulo  ...  tipo     score
17507  CRDLI_IGDLV  Comentarios reales de los incas  ...   PER  0.156536
18283  CRDLI_IGDLV  Comentarios reales de los incas  ...  MISC  0.295542
16433  CRDLI_IGDLV  Comentarios reales de los incas  ...   ORG  0.296423
18506  CRDLI_IGDLV  Comentarios reales de los incas  ...   PER  0.314076
15264  CRDLI_IGDLV  Comentarios reales de los incas  ...   PER  0.321484
19121  CRDLI_IGDLV  Comentarios reales de los incas  ...   ORG  0.325116
14023  CRDLI_IGDLV  Comentarios reales de los incas  ...   PER  0.332770
16516  CRDLI_IGDLV  Comentarios reales de los incas  ...  MISC  0.333013
771      CELC_MVLL      Conversación en La Catedral  ...   ORG  0.335428
10331    CELC_MVLL      Conversación en La Catedral  ...   PER  0.344650

[10 rows x 7 columns]

Esta es la parte que más tiempo toma en ejecución ya que se analizan todos los bloques de ambos libros, en pocas palabras se analizan ambos libros completos

# 11. Normalización y depuración de entidades

Las entidades extraídas por Flair pueden presentar variaciones de escritura debido al contexto narrativo, uso de mayúsculas/minúsculas, signos de puntuación o apodos literarios.

Para reducir duplicados y mejorar la coherencia del análisis, en esta etapa se realiza:

- limpieza de espacios y caracteres residuales;
- normalización textual;
- unificación en minúsculas para comparación interna;
- agrupación de alias y apodos mediante un diccionario manual;
- construcción de una forma canónica por personaje.

Este proceso es especialmente importante en *Conversación en La Catedral*, donde varios personajes son mencionados mediante apodos, sobrenombres o variantes contextuales.

In [0]:
df_entidades_limpio = df_entidades.copy()
display(df_entidades_limpio.head())

obra,titulo,autor,bloque_id,entidad,tipo,score
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,La Catedral,LOC,0.9997674822807312
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Mario Vargas Llosa,PER,0.9998625914255778
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,La Crónica,LOC,0.9999179244041443
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Santiago,PER,0.998166024684906
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,avenida Tacna,LOC,0.9997281134128571

In [0]:
import unicodedata

# Función de normalización textual

def normalizar_texto_entidad(texto):

    """
    Normaliza entidades para comparación interna.

    Esta función:
    - conserva acentos;
    - convierte a minúsculas;
    - elimina espacios repetidos;
    - elimina signos laterales.
    """

    if pd.isna(texto):
        return texto

    texto = str(texto)

    # Unicode consistente
    texto = unicodedata.normalize("NFKC", texto)

    # Minúsculas SOLO para comparación
    texto = texto.lower()

    # Espacios repetidos
    texto = re.sub(r"\s+", " ", texto)

    # Eliminar signos laterales
    texto = texto.strip(".,;:¡!¿?()[]{}\"'")

    return texto.strip()

In [0]:
# Crear columna normalizada interna

df_entidades_limpio["entidad_norm"] = (
    df_entidades_limpio["entidad"]
    .apply(normalizar_texto_entidad)
)

# Normalizar etiquetas
df_entidades_limpio["tipo"] = (
    df_entidades_limpio["tipo"]
    .astype(str)
    .str.upper()
)

display(
    df_entidades_limpio[
        ["entidad", "entidad_norm", "tipo"]
    ].head(20)
)

entidad,entidad_norm,tipo
La Catedral,la catedral,LOC
Mario Vargas Llosa,mario vargas llosa,PER
La Crónica,la crónica,LOC
Santiago,santiago,PER
avenida Tacna,avenida tacna,LOC
Perú,perú,LOC
Wilson,wilson,PER
Colmena,colmena,LOC
Plaza San Martín,plaza san martín,LOC
Perú,perú,LOC
Zavalita,zavalita,PER
Hotel Crillón,hotel crillón,LOC
Perú,perú,LOC
Carlitos,carlitos,PER
Miraflores,miraflores,LOC
Plaza,plaza,LOC
Norwin,norwin,PER
Bar Zela,bar zela,LOC
Zavalita,zavalita,PER
Santiago,santiago,PER

In [0]:
df_entidades_limpio = df_entidades_limpio[
    df_entidades_limpio["entidad_norm"].str.len() > 2
].copy()

df_entidades_limpio = df_entidades_limpio[
    ~df_entidades_limpio["entidad_norm"].str.isnumeric()
].copy()

display(df_entidades_limpio.head())

obra,titulo,autor,bloque_id,entidad,tipo,score,entidad_norm
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,La Catedral,LOC,0.9997674822807312,la catedral
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Mario Vargas Llosa,PER,0.9998625914255778,mario vargas llosa
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,La Crónica,LOC,0.9999179244041443,la crónica
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Santiago,PER,0.998166024684906,santiago
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,avenida Tacna,LOC,0.9997281134128571,avenida tacna

In [0]:
# Diccionario de alias para Conversación en La Catedral

diccionario_alias_personajes = {

    "santiago": "Santiago Zavala",
    "zavalita": "Santiago Zavala",
    "santiago zavala": "Santiago Zavala",
    "santiaguito": "Santiago Zavala",
    "el flaco": "Santiago Zavala",

    "don fermín": "Fermín Zavala",
    "fermín": "Fermín Zavala",
    "fermín zavala": "Fermín Zavala",
    "bola de oro": "Fermín Zavala",

    "cayo": "Cayo Bermúdez",
    "cayo bermúdez": "Cayo Bermúdez",
    "bermúdez": "Cayo Bermúdez",
    "don cayo": "Cayo Bermúdez",
    "cayo mierda": "Cayo Bermúdez",

    "hortensia": "Hortensia",
    "la musa": "Hortensia",

    "ambrosio": "Ambrosio Pardo",
    "ambrosio pardo": "Ambrosio Pardo",
    "el zambo ambrosio": "Ambrosio Pardo",
    "zambo ambrosio": "Ambrosio Pardo",
    "el zambo": "Ambrosio Pardo",

    "amalia": "Amalia Landa",
    "amalita": "Amalia Landa",
    "amalia landa": "Amalia Landa",

    "queta": "Queta",
    "la queta": "Queta",

    "el chispas": "Chispas Zavala",
    "chispas": "Chispas Zavala",
    "teté": "Teté Zavala",
    "la teté": "Teté Zavala",

    "popeye": "Popeye Arévalo",
    "popeye arévalo": "Popeye Arévalo",
    "arévalo": "Popeye Arévalo",
    "aída": "Aída",
    "jacobo": "Jacobo",
    "ana": "Ana",

    "trifulcas": "Trifulcas",
    "ludovico": "Ludovico",
    "hipólito": "Hipólito",
    "lozano": "Coronel Lozano"
}

In [0]:
def resolver_alias_personajes(row):

    entidad_norm = row["entidad_norm"]
    obra = row["obra"]

    # Alias solo para Conversación en La Catedral
    if obra == "CELC_MVLL":

        return diccionario_alias_personajes.get(
            entidad_norm,
            row["entidad"]
        )

    # Otras obras conservan entidad original
    return row["entidad"]

In [0]:
df_entidades_limpio["entidad_canonica"] = (
    df_entidades_limpio.apply(
        resolver_alias_personajes,
        axis=1
    )
)

display(
    df_entidades_limpio[
        ["entidad", "entidad_norm", "entidad_canonica"]
    ].head(20)
)

entidad,entidad_norm,entidad_canonica
La Catedral,la catedral,La Catedral
Mario Vargas Llosa,mario vargas llosa,Mario Vargas Llosa
La Crónica,la crónica,La Crónica
Santiago,santiago,Santiago Zavala
avenida Tacna,avenida tacna,avenida Tacna
Perú,perú,Perú
Wilson,wilson,Wilson
Colmena,colmena,Colmena
Plaza San Martín,plaza san martín,Plaza San Martín
Perú,perú,Perú
Zavalita,zavalita,Santiago Zavala
Hotel Crillón,hotel crillón,Hotel Crillón
Perú,perú,Perú
Carlitos,carlitos,Carlitos
Miraflores,miraflores,Miraflores
Plaza,plaza,Plaza
Norwin,norwin,Norwin
Bar Zela,bar zela,Bar Zela
Zavalita,zavalita,Santiago Zavala
Santiago,santiago,Santiago Zavala

In [0]:
df_entidades_limpio["entidad_canonica"] = (
    df_entidades_limpio["entidad_canonica"]
    .astype(str)
    .str.strip()
)

In [0]:
print("Total de entidades originales:", len(df_entidades))
print("Total de entidades depuradas:", len(df_entidades_limpio))
print("Tipos de entidades encontrados:", df_entidades_limpio["tipo"].unique())
print("Obras analizadas:", df_entidades_limpio["obra"].unique())

Total de entidades originales: 21493
Total de entidades depuradas: 21468
Tipos de entidades encontrados: ['LOC' 'PER' 'MISC' 'ORG']
Obras analizadas: ['CELC_MVLL' 'CRDLI_IGDLV']

**Resultado esperado:** después de la limpieza debe mantenerse una cantidad suficiente de entidades para el análisis, pero con menos ruido textual. Si se observan demasiados falsos positivos, se puede activar el filtro por `UMBRAL_SCORE_NER`.

# 12. Análisis exploratorio de entidades

Esta sección resume las entidades en detectadas `df_entidades` mediante tablas de frecuencia, distribución por tipo, comparación entre obras y densidad por bloque.

El objetivo es obtener una primera lectura cuantitativa: qué tipos de entidades predominan, cuáles son las entidades más frecuentes y en qué partes del texto se concentran más menciones.

In [0]:
resumen_tipos = (
    df_entidades_limpio
    .groupby(["obra","tipo"])
    .size()
    .reset_index(name="cantidad")
    #.sort_values(["obra", "cantidad"], ascending=False)
)

display(resumen_tipos)

obra,tipo,cantidad
CELC_MVLL,LOC,1368
CELC_MVLL,MISC,577
CELC_MVLL,ORG,624
CELC_MVLL,PER,10162
CRDLI_IGDLV,LOC,2698
CRDLI_IGDLV,MISC,2126
CRDLI_IGDLV,ORG,596
CRDLI_IGDLV,PER,3317

In [0]:
frecuencia_entidades_obra = (
    df_entidades_limpio
    .groupby(["obra", "entidad_norm", "tipo"])
    .size()
    .reset_index(name="frecuencia")
    .sort_values(["obra", "frecuencia"], ascending=[True, False])
)

display(frecuencia_entidades_obra.head(10))

obra,entidad_norm,tipo,frecuencia
CELC_MVLL,ambrosio,PER,798
CELC_MVLL,santiago,PER,776
CELC_MVLL,amalia,PER,621
CELC_MVLL,queta,PER,407
CELC_MVLL,zavalita,PER,376
CELC_MVLL,cayo,PER,336
CELC_MVLL,ludovico,PER,321
CELC_MVLL,fermín,PER,285
CELC_MVLL,carlitos,PER,271
CELC_MVLL,chispas,PER,234

In [0]:
display(frecuencia_entidades_obra[frecuencia_entidades_obra["obra"] == "CRDLI_IGDLV"].head(10))

obra,entidad_norm,tipo,frecuencia
CRDLI_IGDLV,inca,PER,642
CRDLI_IGDLV,sol,MISC,467
CRDLI_IGDLV,incas,MISC,366
CRDLI_IGDLV,perú,LOC,363
CRDLI_IGDLV,cozco,LOC,354
CRDLI_IGDLV,rey,PER,235
CRDLI_IGDLV,incas,ORG,212
CRDLI_IGDLV,reyes,PER,189
CRDLI_IGDLV,españa,LOC,163
CRDLI_IGDLV,inca,MISC,158

In [0]:
top_n = 20

top_entidades_por_obra = (
    frecuencia_entidades_obra
    .groupby("obra", group_keys=False)
    .head(top_n)
)

display(top_entidades_por_obra)

obra,entidad_norm,tipo,frecuencia
CELC_MVLL,ambrosio,PER,798
CELC_MVLL,santiago,PER,776
CELC_MVLL,amalia,PER,621
CELC_MVLL,queta,PER,407
CELC_MVLL,zavalita,PER,376
CELC_MVLL,cayo,PER,336
CELC_MVLL,ludovico,PER,321
CELC_MVLL,fermín,PER,285
CELC_MVLL,carlitos,PER,271
CELC_MVLL,chispas,PER,234
CELC_MVLL,bermúdez,PER,227
CELC_MVLL,lozano,PER,197
CELC_MVLL,don,PER,196
CELC_MVLL,teté,PER,174
CELC_MVLL,trifulcio,PER,173
CELC_MVLL,popeye,PER,172
CELC_MVLL,aída,PER,149
CELC_MVLL,becerrita,PER,130
CELC_MVLL,ana,PER,127
CELC_MVLL,hipólito,PER,124
CRDLI_IGDLV,inca,PER,642
CRDLI_IGDLV,sol,MISC,467
CRDLI_IGDLV,incas,MISC,366
CRDLI_IGDLV,perú,LOC,363
CRDLI_IGDLV,cozco,LOC,354
CRDLI_IGDLV,rey,PER,235
CRDLI_IGDLV,incas,ORG,212
CRDLI_IGDLV,reyes,PER,189
CRDLI_IGDLV,españa,LOC,163
CRDLI_IGDLV,inca,MISC,158
CRDLI_IGDLV,sol,PER,132
CRDLI_IGDLV,imperio,ORG,121
CRDLI_IGDLV,incas,PER,107
CRDLI_IGDLV,huayna cápac,PER,92
CRDLI_IGDLV,dios,MISC,91
CRDLI_IGDLV,imperio,MISC,85
CRDLI_IGDLV,inca,ORG,77
CRDLI_IGDLV,atahuallpa,PER,74
CRDLI_IGDLV,reyes incas,PER,71
CRDLI_IGDLV,inca viracocha,PER,68

In [0]:
comparacion_tipos_obra = (
    df_entidades_limpio
    .groupby(["obra", "tipo"])
    .size()
    .reset_index(name="cantidad")
    .sort_values(["obra", "cantidad"], ascending=[True, False])
)

display(comparacion_tipos_obra)

obra,tipo,cantidad
CELC_MVLL,PER,10162
CELC_MVLL,LOC,1368
CELC_MVLL,ORG,624
CELC_MVLL,MISC,577
CRDLI_IGDLV,PER,3317
CRDLI_IGDLV,LOC,2698
CRDLI_IGDLV,MISC,2126
CRDLI_IGDLV,ORG,596

In [0]:
comparacion_pivot = comparacion_tipos_obra.pivot_table(
    index="obra",
    columns="tipo",
    values="cantidad",
    fill_value=0
).reset_index()

display(comparacion_pivot)

obra,LOC,MISC,ORG,PER
CELC_MVLL,1368.0,577.0,624.0,10162.0
CRDLI_IGDLV,2698.0,2126.0,596.0,3317.0

In [0]:
comparacion_tipos_obra["porcentaje"] = (
    comparacion_tipos_obra
    .groupby("obra")["cantidad"]
    .transform(lambda x: x / x.sum() * 100)
)

comparacion_tipos_obra["porcentaje"] = comparacion_tipos_obra["porcentaje"].round(2)

display(comparacion_tipos_obra)

obra,tipo,cantidad,porcentaje
CELC_MVLL,PER,10162,79.82
CELC_MVLL,LOC,1368,10.75
CELC_MVLL,ORG,624,4.9
CELC_MVLL,MISC,577,4.53
CRDLI_IGDLV,PER,3317,37.96
CRDLI_IGDLV,LOC,2698,30.88
CRDLI_IGDLV,MISC,2126,24.33
CRDLI_IGDLV,ORG,596,6.82

In [0]:
import plotly.express as px

fig = px.bar(
    comparacion_tipos_obra,
    x="tipo",
    y="porcentaje",
    color="obra",
    barmode="group",
    text="porcentaje",
    title="Comparación porcentual de tipos de entidad entre obras",
    labels={
        "tipo": "Tipo de entidad",
        "porcentaje": "Porcentaje (%)",
        "obra": "Obra"
    },
    hover_data={
        "cantidad": True,
        "porcentaje": ':.2f'
    },
    height=500
)

fig.update_traces(
    texttemplate="%{text:.2f}%",
    textposition="outside"
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white"
)

fig.show()

In [0]:
entidades_por_bloque = (
    df_entidades_limpio
    .groupby(["obra", "titulo", "bloque_id", "tipo"])
    .size()
    .reset_index(name="cantidad")
    .sort_values(["obra", "bloque_id", "cantidad"], ascending=[True, True, False])
)

display(entidades_por_bloque.head(50))

obra,titulo,bloque_id,tipo,cantidad
CELC_MVLL,Conversación en La Catedral,1,PER,35
CELC_MVLL,Conversación en La Catedral,1,LOC,15
CELC_MVLL,Conversación en La Catedral,1,MISC,3
CELC_MVLL,Conversación en La Catedral,1,ORG,1
CELC_MVLL,Conversación en La Catedral,2,PER,14
CELC_MVLL,Conversación en La Catedral,2,LOC,5
CELC_MVLL,Conversación en La Catedral,2,MISC,4
CELC_MVLL,Conversación en La Catedral,2,ORG,1
CELC_MVLL,Conversación en La Catedral,3,LOC,21
CELC_MVLL,Conversación en La Catedral,3,PER,17
CELC_MVLL,Conversación en La Catedral,3,MISC,2
CELC_MVLL,Conversación en La Catedral,4,LOC,15
CELC_MVLL,Conversación en La Catedral,4,PER,8
CELC_MVLL,Conversación en La Catedral,4,ORG,2
CELC_MVLL,Conversación en La Catedral,4,MISC,1
CELC_MVLL,Conversación en La Catedral,5,PER,16
CELC_MVLL,Conversación en La Catedral,5,ORG,2
CELC_MVLL,Conversación en La Catedral,5,LOC,1
CELC_MVLL,Conversación en La Catedral,5,MISC,1
CELC_MVLL,Conversación en La Catedral,6,PER,17
CELC_MVLL,Conversación en La Catedral,6,LOC,4
CELC_MVLL,Conversación en La Catedral,6,MISC,3
CELC_MVLL,Conversación en La Catedral,6,ORG,1
CELC_MVLL,Conversación en La Catedral,7,PER,18
CELC_MVLL,Conversación en La Catedral,7,LOC,4
CELC_MVLL,Conversación en La Catedral,7,MISC,3
CELC_MVLL,Conversación en La Catedral,8,PER,20
CELC_MVLL,Conversación en La Catedral,8,LOC,3
CELC_MVLL,Conversación en La Catedral,8,MISC,2
CELC_MVLL,Conversación en La Catedral,9,PER,15
CELC_MVLL,Conversación en La Catedral,9,LOC,4
CELC_MVLL,Conversación en La Catedral,9,MISC,1
CELC_MVLL,Conversación en La Catedral,10,PER,21
CELC_MVLL,Conversación en La Catedral,10,LOC,10
CELC_MVLL,Conversación en La Catedral,10,MISC,2
CELC_MVLL,Conversación en La Catedral,11,PER,8
CELC_MVLL,Conversación en La Catedral,11,LOC,4
CELC_MVLL,Conversación en La Catedral,11,MISC,1
CELC_MVLL,Conversación en La Catedral,12,PER,27
CELC_MVLL,Conversación en La Catedral,12,LOC,9
CELC_MVLL,Conversación en La Catedral,12,MISC,2
CELC_MVLL,Conversación en La Catedral,12,ORG,2
CELC_MVLL,Conversación en La Catedral,13,PER,39
CELC_MVLL,Conversación en La Catedral,13,LOC,7
CELC_MVLL,Conversación en La Catedral,13,ORG,7
CELC_MVLL,Conversación en La Catedral,13,MISC,3
CELC_MVLL,Conversación en La Catedral,14,PER,37
CELC_MVLL,Conversación en La Catedral,14,MISC,4
CELC_MVLL,Conversación en La Catedral,14,ORG,3
CELC_MVLL,Conversación en La Catedral,14,LOC,2

In [0]:
densidad_entidades_bloque = (
    df_entidades_limpio
    .groupby(["obra", "titulo", "bloque_id"])
    .size()
    .reset_index(name="total_entidades")
)

df_bloques_palabras = df_bloques.copy()

df_bloques_palabras["total_palabras"] = (
    df_bloques_palabras["texto_bloque"]
    .astype(str)
    .apply(lambda x: len(x.split()))
)

densidad_entidades_bloque = densidad_entidades_bloque.merge(
    df_bloques_palabras[["obra", "titulo", "bloque_id", "total_palabras"]],
    on=["obra", "titulo", "bloque_id"],
    how="left"
)

densidad_entidades_bloque["entidades_por_1000_palabras"] = (
    densidad_entidades_bloque["total_entidades"] 
    / densidad_entidades_bloque["total_palabras"] * 1000
).round(2)

display(densidad_entidades_bloque.head(30))

obra,titulo,bloque_id,total_entidades,total_palabras,entidades_por_1000_palabras
CELC_MVLL,Conversación en La Catedral,1,54,688,78.49
CELC_MVLL,Conversación en La Catedral,2,24,241,99.59
CELC_MVLL,Conversación en La Catedral,3,40,693,57.72
CELC_MVLL,Conversación en La Catedral,4,26,555,46.85
CELC_MVLL,Conversación en La Catedral,5,20,698,28.65
CELC_MVLL,Conversación en La Catedral,6,25,699,35.77
CELC_MVLL,Conversación en La Catedral,7,25,490,51.02
CELC_MVLL,Conversación en La Catedral,8,25,868,28.8
CELC_MVLL,Conversación en La Catedral,9,20,698,28.65
CELC_MVLL,Conversación en La Catedral,10,33,647,51.0
CELC_MVLL,Conversación en La Catedral,11,13,254,51.18
CELC_MVLL,Conversación en La Catedral,12,40,685,58.39
CELC_MVLL,Conversación en La Catedral,13,56,696,80.46
CELC_MVLL,Conversación en La Catedral,14,46,559,82.29
CELC_MVLL,Conversación en La Catedral,15,44,690,63.77
CELC_MVLL,Conversación en La Catedral,16,52,685,75.91
CELC_MVLL,Conversación en La Catedral,17,25,422,59.24
CELC_MVLL,Conversación en La Catedral,18,43,679,63.33
CELC_MVLL,Conversación en La Catedral,19,33,676,48.82
CELC_MVLL,Conversación en La Catedral,20,45,685,65.69
CELC_MVLL,Conversación en La Catedral,21,50,688,72.67
CELC_MVLL,Conversación en La Catedral,22,20,413,48.43
CELC_MVLL,Conversación en La Catedral,23,51,605,84.3
CELC_MVLL,Conversación en La Catedral,24,44,688,63.95
CELC_MVLL,Conversación en La Catedral,25,38,687,55.31
CELC_MVLL,Conversación en La Catedral,26,20,225,88.89
CELC_MVLL,Conversación en La Catedral,27,56,799,70.09
CELC_MVLL,Conversación en La Catedral,28,35,383,91.38
CELC_MVLL,Conversación en La Catedral,29,42,685,61.31
CELC_MVLL,Conversación en La Catedral,30,36,655,54.96

$$
densidad \ de \ entidades = \frac{cantidad \ de \ entidades} {cantidad \ de \ palabras \ del \ bloque}
$$

In [0]:
bloques_mas_entidades = (
    densidad_entidades_bloque
    .sort_values(["obra", "total_entidades"], ascending=[True, False])
    .groupby("obra", group_keys=False)
    .head(10)
)

display(bloques_mas_entidades)

obra,titulo,bloque_id,total_entidades,total_palabras,entidades_por_1000_palabras
CELC_MVLL,Conversación en La Catedral,320,81,682,118.77
CELC_MVLL,Conversación en La Catedral,213,79,693,114.0
CELC_MVLL,Conversación en La Catedral,149,78,749,104.14
CELC_MVLL,Conversación en La Catedral,281,72,914,78.77
CELC_MVLL,Conversación en La Catedral,310,71,693,102.45
CELC_MVLL,Conversación en La Catedral,311,70,674,103.86
CELC_MVLL,Conversación en La Catedral,308,68,692,98.27
CELC_MVLL,Conversación en La Catedral,319,68,667,101.95
CELC_MVLL,Conversación en La Catedral,204,67,689,97.24
CELC_MVLL,Conversación en La Catedral,32,66,976,67.62
CRDLI_IGDLV,Comentarios reales de los incas,255,55,700,78.57
CRDLI_IGDLV,Comentarios reales de los incas,8,54,699,77.25
CRDLI_IGDLV,Comentarios reales de los incas,35,52,699,74.39
CRDLI_IGDLV,Comentarios reales de los incas,254,51,692,73.7
CRDLI_IGDLV,Comentarios reales de los incas,383,49,696,70.4
CRDLI_IGDLV,Comentarios reales de los incas,106,48,694,69.16
CRDLI_IGDLV,Comentarios reales de los incas,332,48,697,68.87
CRDLI_IGDLV,Comentarios reales de los incas,10,47,694,67.72
CRDLI_IGDLV,Comentarios reales de los incas,53,46,696,66.09
CRDLI_IGDLV,Comentarios reales de los incas,185,45,694,64.84

In [0]:
bloques_mayor_densidad = (
    densidad_entidades_bloque
    .sort_values(["obra", "entidades_por_1000_palabras"], ascending=[True, False])
    .groupby("obra", group_keys=False)
    .head(10)
)

display(bloques_mayor_densidad)

obra,titulo,bloque_id,total_entidades,total_palabras,entidades_por_1000_palabras
CELC_MVLL,Conversación en La Catedral,323,54,420,128.57
CELC_MVLL,Conversación en La Catedral,320,81,682,118.77
CELC_MVLL,Conversación en La Catedral,213,79,693,114.0
CELC_MVLL,Conversación en La Catedral,146,25,239,104.6
CELC_MVLL,Conversación en La Catedral,149,78,749,104.14
CELC_MVLL,Conversación en La Catedral,311,70,674,103.86
CELC_MVLL,Conversación en La Catedral,310,71,693,102.45
CELC_MVLL,Conversación en La Catedral,319,68,667,101.95
CELC_MVLL,Conversación en La Catedral,312,66,662,99.7
CELC_MVLL,Conversación en La Catedral,2,24,241,99.59
CRDLI_IGDLV,Comentarios reales de los incas,255,55,700,78.57
CRDLI_IGDLV,Comentarios reales de los incas,8,54,699,77.25
CRDLI_IGDLV,Comentarios reales de los incas,35,52,699,74.39
CRDLI_IGDLV,Comentarios reales de los incas,254,51,692,73.7
CRDLI_IGDLV,Comentarios reales de los incas,383,49,696,70.4
CRDLI_IGDLV,Comentarios reales de los incas,106,48,694,69.16
CRDLI_IGDLV,Comentarios reales de los incas,332,48,697,68.87
CRDLI_IGDLV,Comentarios reales de los incas,10,47,694,67.72
CRDLI_IGDLV,Comentarios reales de los incas,53,46,696,66.09
CRDLI_IGDLV,Comentarios reales de los incas,185,45,694,64.84

La densidad por cada 1000 palabras permite comparar bloques de distinto tamaño. Un bloque con mayor densidad concentra más entidades en relación con su extensión.

In [0]:
for obra in densidad_entidades_bloque["obra"].unique():

    data = densidad_entidades_bloque[
        densidad_entidades_bloque["obra"] == obra
    ]

    fig = px.line(
        data,
        x="bloque_id",
        y="entidades_por_1000_palabras",
        markers=True,
        title=f"Densidad de entidades por bloque - {obra}",
        labels={
            "bloque_id": "Bloque",
            "entidades_por_1000_palabras": "Entidades por 1000 palabras"
        },
        height=500
    )

    # Hover personalizado
    fig.update_traces(
        hovertemplate=
        "<b>Bloque:</b> %{x}<br>" +
        "<b>Densidad:</b> %{y:.2f}<extra></extra>"
    )

    # Estética
    fig.update_layout(
        title_x=0.5,
        template="plotly_white"
    )

    fig.show()

# 13. Análisis de personajes

Para aproximar la extracción de personajes, se filtran las entidades de tipo `PER`. En textos literarios este tipo puede incluir personajes ficticios, autores, figuras históricas o personas mencionadas dentro del relato.

El análisis considera frecuencia total, score promedio del modelo y cantidad de bloques distintos donde aparece cada entidad.

In [0]:
# si no se trato antes en la normalizacion, seria conveniente descomentar esta linea, pero como ya lo hicimos no es necesario, de hecho podría perjudicar al analisis
# df_entidades_limpio["entidad_canonica"] = df_entidades_limpio["entidad_canonica"].replace(
#     diccionario_alias_personajes
# )

com.databricks.backend.common.rpc.CommandSkippedException
	at com.databricks.spark.chauffeur.SequenceExecutionState.$anonfun$cancel$3(SequenceExecutionState.scala:141)
	at com.databricks.spark.chauffeur.SequenceExecutionState.$anonfun$cancel$3$adapted(SequenceExecutionState.scala:136)
	at scala.collection.immutable.Range.foreach(Range.scala:192)
	at com.databricks.spark.chauffeur.SequenceExecutionState.cancel(SequenceExecutionState.scala:136)
	at com.databricks.spark.chauffeur.ExecContextState.cancelRunningSequence(ExecContextState.scala:725)
	at com.databricks.spark.chauffeur.ExecContextState.$anonfun$cancel$1(ExecContextState.scala:443)
	at scala.Option.getOrElse(Option.scala:201)
	at com.databricks.spark.chauffeur.ExecContextState.cancel(ExecContextState.scala:443)
	at com.databricks.spark.chauffeur.ExecutionContextManagerV1.cancelExecution(ExecutionContextManagerV1.scala:503)
	at com.databricks.spark.chauffeur.ChauffeurState.$anonfun$process$1(ChauffeurState.scala:794)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperation$1(UsageLogging.scala:531)
	at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:669)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$6(UsageLogging.scala:696)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.spark.chauffeur.ChauffeurState.withAttributionContext(ChauffeurState.scala:74)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags(AttributionContextTracing.scala:201)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags$(AttributionContextTracing.scala:182)
	at com.databricks.spark.chauffeur.ChauffeurState.withAttributionTags(ChauffeurState.scala:74)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$5(UsageLogging.scala:664)
	at com.databricks.logging.UsageLogging.withOtelSpanInContext$1(UsageLogging.scala:656)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:659)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:540)
	at com.databricks.spark.chauffeur.ChauffeurState.recordOperationWithResultTags(ChauffeurState.scala:74)
	at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:532)
	at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:496)
	at com.databricks.spark.chauffeur.ChauffeurState.recordOperation(ChauffeurState.scala:74)
	at com.databricks.spark.chauffeur.ChauffeurState.process(ChauffeurState.scala:766)
	at com.databricks.spark.chauffeur.Chauffeur.handleDriverRequest$1(Chauffeur.scala:842)
	at com.databricks.spark.chauffeur.Chauffeur.$anonfun$handleDriverRequests$2(Chauffeur.scala:869)
	at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:669)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$6(UsageLogging.scala:696)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.spark.chauffeur.Chauffeur.withAttributionContext(Chauffeur.scala:145)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags(AttributionContextTracing.scala:201)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags$(AttributionContextTracing.scala:182)
	at com.databricks.spark.chauffeur.Chauffeur.withAttributionTags(Chauffeur.scala:145)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$5(UsageLogging.scala:664)
	at com.databricks.logging.UsageLogging.withOtelSpanInContext$1(UsageLogging.scala:656)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:659)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:540)
	at com.databricks.spark.chauffeur.Chauffeur.recordOperationWithResultTags(Chauffeur.scala:145)
	at com.databricks.spark.chauffeur.Chauffeur.handleDriverRequestWithUsageLogging$1(Chauffeur.scala:868)
	at com.databricks.spark.chauffeur.Chauffeur.handleDriverRequests(Chauffeur.scala:919)
	at com.databricks.spark.chauffeur.ChauffeurCompatServerBackend.$anonfun$new$17(ChauffeurCompatServerBackend.scala:208)
	at com.databricks.spark.chauffeur.ChauffeurCompatServerBackend.$anonfun$new$17$adapted(ChauffeurCompatServerBackend.scala:207)
	at com.databricks.rpc.armeria.UnaryRpcHandler$.$anonfun$legacyWithRPCContext$1(UnaryRpcHandler.scala:517)
	at com.databricks.rpc.armeria.UnaryRpcHandler.$anonfun$callFunc$2(UnaryRpcHandler.scala:319)
	at com.databricks.rpc.armeria.Util$.handleUnexpectedExceptions(Util.scala:87)
	at com.databricks.rpc.armeria.UnaryRpcHandler.callFunc(UnaryRpcHandler.scala:319)
	at com.databricks.rpc.armeria.UnaryRpcHandlerInternal.callFuncWithHooks(UnaryRpcHandler.scala:647)
	at com.databricks.rpc.armeria.UnaryRpcHandlerInternal.$anonfun$callFunc$3(UnaryRpcHandler.scala:625)
	at com.databricks.rpc.OperationSpan.$anonfun$wrapFuture$1(OperationSpan.scala:69)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.rpc.OperationSpan.withAttributionContext(OperationSpan.scala:22)
	at com.databricks.rpc.OperationSpan.wrapFuture(OperationSpan.scala:68)
	at com.databricks.rpc.armeria.UnaryRpcHandlerInternal.callFunc(UnaryRpcHandler.scala:623)
	at com.databricks.rpc.armeria.UnaryRpcHandler.$anonfun$handleRpc0$3(UnaryRpcHandler.scala:276)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.rpc.armeria.UnaryRpcHandler.withAttributionContext(UnaryRpcHandler.scala:43)
	at com.databricks.rpc.armeria.UnaryRpcHandler.$anonfun$handleRpc0$2(UnaryRpcHandler.scala:236)
	at com.databricks.context.integrity.IntegrityCheckContext$ThreadLocalStorage$.withValue(IntegrityCheckContext.scala:76)
	at com.databricks.rpc.armeria.UnaryRpcHandler.handleRpc0(UnaryRpcHandler.scala:236)
	at com.databricks.rpc.armeria.UnaryRpcHandler.$anonfun$handleRpc$1(UnaryRpcHandler.scala:207)
	at com.databricks.rpc.armeria.server.internal.RequestCompletionTracker.wrap(RequestCompletionTracker.scala:184)
	at com.databricks.rpc.armeria.UnaryRpcHandler.handleRpc(UnaryRpcHandler.scala:207)
	at com.databricks.rpc.armeria.UnaryRpcHandler.handleJettyRpc(UnaryRpcHandler.scala:88)
	at com.databricks.rpc.armeria.UnaryRpcServiceInternal.handleJettyRpcWithAggregatedContent(UnaryRpcService.scala:528)
	at com.databricks.rpc.armeria.UnaryRpcServiceInternal.$anonfun$handleContextAwareJettyRpcWithAggregatedContent$2(UnaryRpcService.scala:439)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.rpc.armeria.UnaryRpcServiceInternal.withAttributionContext(UnaryRpcService.scala:189)
	at com.databricks.rpc.armeria.UnaryRpcServiceInternal.$anonfun$handleContextAwareJettyRpcWithAggregatedContent$1(UnaryRpcService.scala:434)
	at com.databricks.context.integrity.IntegrityCheckContext$ThreadLocalStorage$.withValue(IntegrityCheckContext.scala:76)
	at com.databricks.rpc.armeria.UnaryRpcServiceInternal.handleContextAwareJettyRpcWithAggregatedContent(UnaryRpcService.scala:433)
	at com.databricks.rpc.armeria.UnaryRpcServiceInternal.$anonfun$handleJettyJsonRpc$2(UnaryRpcService.scala:413)
	at com.databricks.rpc.armeria.Util$.handleUnexpectedExceptions(Util.scala:87)
	at com.databricks.rpc.armeria.Util$.handleUnexpectedExceptions(Util.scala:111)
	at com.databricks.rpc.armeria.UnaryRpcServiceInternal.$anonfun$handleJettyJsonRpc$1(UnaryRpcService.scala:408)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:481)
	at com.databricks.threading.DatabricksExecutionContext$InstrumentedRunnable.run(DatabricksExecutionContext.scala:36)
	at grpc_shaded.com.linecorp.armeria.common.DefaultContextAwareRunnable.run(DefaultContextAwareRunnable.java:45)
	at com.databricks.threading.ContextBoundRunnable.$anonfun$run$2(ContextBoundRunnable.scala:16)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.threading.ContextBoundRunnable.withAttributionContext(ContextBoundRunnable.scala:7)
	at com.databricks.threading.ContextBoundRunnable.$anonfun$run$1(ContextBoundRunnable.scala:16)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.context.integrity.IntegrityCheckContext$ThreadLocalStorage$.withValue(IntegrityCheckContext.scala:76)
	at com.databricks.threading.ContextBoundRunnable.run(ContextBoundRunnable.scala:15)
	at com.databricks.threading.InstrumentedExecutorService.$anonfun$makeContextAware$2(InstrumentedExecutorService.scala:257)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.threading.InstrumentedExecutorService.$anonfun$instrumentationWrapper$1(InstrumentedExecutorService.scala:299)
	at com.databricks.instrumentation.QueuedThreadPoolInstrumenter.trackActiveThreads(QueuedThreadPoolInstrumenter.scala:132)
	at com.databricks.instrumentation.QueuedThreadPoolInstrumenter.trackActiveThreads$(QueuedThreadPoolInstrumenter.scala:129)
	at com.databricks.threading.InstrumentedExecutorService.trackActiveThreads(InstrumentedExecutorService.scala:72)
	at com.databricks.threading.InstrumentedExecutorService.instrumentationWrapper(InstrumentedExecutorService.scala:287)
	at com.databricks.threading.InstrumentedExecutorService.$anonfun$makeContextAware$1(InstrumentedExecutorService.scala:259)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

In [0]:
df_personajes = df_entidades_limpio[
    df_entidades_limpio["tipo"] == "PER"
].copy()

display(df_personajes.head(10))

obra,titulo,autor,bloque_id,entidad,tipo,score,entidad_norm,entidad_canonica
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Mario Vargas Llosa,PER,0.9998625914255778,mario vargas llosa,Mario Vargas Llosa
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Santiago,PER,0.998166024684906,santiago,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Wilson,PER,0.9970278143882751,wilson,Wilson
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Zavalita,PER,0.9991453886032104,zavalita,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Carlitos,PER,0.9990795850753784,carlitos,Carlitos
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Norwin,PER,0.9999306201934814,norwin,Norwin
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Zavalita,PER,0.999855637550354,zavalita,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Santiago,PER,0.999618411064148,santiago,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Norwin,PER,0.9999040365219116,norwin,Norwin
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Director,PER,0.9996047616004944,director,Director

In [0]:
personajes_por_obra = (
    df_personajes
    .groupby(["obra", "entidad_canonica"])
    .agg(
        frecuencia=("entidad_canonica", "count"),
        score_promedio=("score", "mean"),
        bloques_distintos=("bloque_id", "nunique")
    )
    .reset_index()
    .sort_values(["obra", "frecuencia"], ascending=[True, False])
)

personajes_por_obra["score_promedio"] = personajes_por_obra["score_promedio"].round(4)

display(personajes_por_obra.head(50))

obra,entidad_canonica,frecuencia,score_promedio,bloques_distintos
CELC_MVLL,Santiago Zavala,1154,0.9986,177
CELC_MVLL,Ambrosio Pardo,799,0.9993,198
CELC_MVLL,Cayo Bermúdez,664,0.959,149
CELC_MVLL,Amalia Landa,631,0.9928,96
CELC_MVLL,Queta,407,0.987,80
CELC_MVLL,Fermín Zavala,354,0.8453,104
CELC_MVLL,Ludovico,321,0.9992,71
CELC_MVLL,Carlitos,271,0.9982,72
CELC_MVLL,Chispas Zavala,234,0.9998,64
CELC_MVLL,Popeye Arévalo,213,0.9961,54
CELC_MVLL,Coronel Lozano,197,0.9902,46
CELC_MVLL,don,178,0.796,75
CELC_MVLL,Teté Zavala,176,0.9945,62
CELC_MVLL,Trifulcio,173,0.9971,35
CELC_MVLL,Aída,149,0.9996,37
CELC_MVLL,Becerrita,130,0.9999,27
CELC_MVLL,Ana,127,0.9983,26
CELC_MVLL,Hipólito,124,0.9992,47
CELC_MVLL,Espina,111,0.9988,40
CELC_MVLL,Jacobo,108,0.9998,29
CELC_MVLL,Hortensia,106,0.9779,51
CELC_MVLL,Landa,106,0.9885,32
CELC_MVLL,Odría,101,0.9887,55
CELC_MVLL,Presidente,100,0.983,45
CELC_MVLL,Paredes,93,0.9977,24
CELC_MVLL,Trinidad,91,0.997,28
CELC_MVLL,Washington,79,0.9991,17
CELC_MVLL,Carlota,77,0.9979,27
CELC_MVLL,Zoila,73,0.9045,37
CELC_MVLL,Ivonne,69,0.9666,28
CELC_MVLL,Molina,69,0.9996,17
CELC_MVLL,Periquito,66,0.9999,22
CELC_MVLL,Robertito,64,0.9997,20
CELC_MVLL,Gertrudis,57,0.9915,14
CELC_MVLL,Quetita,57,0.9985,22
CELC_MVLL,Alcibíades,52,0.9767,19
CELC_MVLL,Téllez,50,0.9997,18
CELC_MVLL,Símula,48,0.9997,22
CELC_MVLL,Héctor,47,0.9997,17
CELC_MVLL,Hilario,46,0.7879,14
CELC_MVLL,Norwin,46,0.9999,18
CELC_MVLL,Arispe,45,0.9998,16
CELC_MVLL,Solórzano,45,0.9999,19
CELC_MVLL,Teniente,41,0.9979,7
CELC_MVLL,Arbeláez,38,0.9563,14
CELC_MVLL,Llerena,38,0.9983,10
CELC_MVLL,Malvina,38,0.9993,9
CELC_MVLL,Serrano,38,0.9992,20
CELC_MVLL,Urondo,38,0.9999,14
CELC_MVLL,Musa,37,0.9853,20

In [0]:
top_personajes_por_obra = (
    personajes_por_obra
    .groupby("obra", group_keys=False)
    .head(20)
)

display(top_personajes_por_obra)

obra,entidad_canonica,frecuencia,score_promedio,bloques_distintos
CELC_MVLL,Santiago Zavala,1154,0.9986,177
CELC_MVLL,Ambrosio Pardo,799,0.9993,198
CELC_MVLL,Cayo Bermúdez,664,0.959,149
CELC_MVLL,Amalia Landa,631,0.9928,96
CELC_MVLL,Queta,407,0.987,80
CELC_MVLL,Fermín Zavala,354,0.8453,104
CELC_MVLL,Ludovico,321,0.9992,71
CELC_MVLL,Carlitos,271,0.9982,72
CELC_MVLL,Chispas Zavala,234,0.9998,64
CELC_MVLL,Popeye Arévalo,213,0.9961,54
CELC_MVLL,Coronel Lozano,197,0.9902,46
CELC_MVLL,don,178,0.796,75
CELC_MVLL,Teté Zavala,176,0.9945,62
CELC_MVLL,Trifulcio,173,0.9971,35
CELC_MVLL,Aída,149,0.9996,37
CELC_MVLL,Becerrita,130,0.9999,27
CELC_MVLL,Ana,127,0.9983,26
CELC_MVLL,Hipólito,124,0.9992,47
CELC_MVLL,Espina,111,0.9988,40
CELC_MVLL,Jacobo,108,0.9998,29
CRDLI_IGDLV,Inca,642,0.94,204
CRDLI_IGDLV,Rey,235,0.9728,144
CRDLI_IGDLV,Reyes,189,0.9695,121
CRDLI_IGDLV,Sol,132,0.8293,68
CRDLI_IGDLV,Incas,107,0.76,71
CRDLI_IGDLV,Huayna Cápac,88,0.9943,44
CRDLI_IGDLV,Atahuallpa,74,0.9879,34
CRDLI_IGDLV,Reyes Incas,66,0.9337,56
CRDLI_IGDLV,Inca Viracocha,61,0.9892,24
CRDLI_IGDLV,Príncipe,51,0.9789,35
CRDLI_IGDLV,Padre Blas Valera,44,0.9998,32
CRDLI_IGDLV,Inca Manco Cápac,31,0.9779,27
CRDLI_IGDLV,Viracocha,27,0.9495,12
CRDLI_IGDLV,Huáscar Inca,24,0.9994,17
CRDLI_IGDLV,Inca Pachacútec,23,0.9428,15
CRDLI_IGDLV,Pedro de Cieza,23,0.9984,19
CRDLI_IGDLV,Túpac Inca Yupanqui,23,0.9989,16
CRDLI_IGDLV,Manco Cápac,22,0.9714,16
CRDLI_IGDLV,Huáscar,21,0.9935,14
CRDLI_IGDLV,Inca Cápac Yupanqui,20,0.9611,12

In [0]:
personajes_por_bloque = (
    df_personajes
    .groupby(["obra", "titulo", "bloque_id"])
    .size()
    .reset_index(name="cantidad_personajes")
    .sort_values(["obra", "bloque_id"])
)

display(personajes_por_bloque.head(50))

obra,titulo,bloque_id,cantidad_personajes
CELC_MVLL,Conversación en La Catedral,1,35
CELC_MVLL,Conversación en La Catedral,2,14
CELC_MVLL,Conversación en La Catedral,3,17
CELC_MVLL,Conversación en La Catedral,4,8
CELC_MVLL,Conversación en La Catedral,5,16
CELC_MVLL,Conversación en La Catedral,6,17
CELC_MVLL,Conversación en La Catedral,7,18
CELC_MVLL,Conversación en La Catedral,8,20
CELC_MVLL,Conversación en La Catedral,9,15
CELC_MVLL,Conversación en La Catedral,10,21
CELC_MVLL,Conversación en La Catedral,11,8
CELC_MVLL,Conversación en La Catedral,12,27
CELC_MVLL,Conversación en La Catedral,13,39
CELC_MVLL,Conversación en La Catedral,14,37
CELC_MVLL,Conversación en La Catedral,15,41
CELC_MVLL,Conversación en La Catedral,16,32
CELC_MVLL,Conversación en La Catedral,17,23
CELC_MVLL,Conversación en La Catedral,18,39
CELC_MVLL,Conversación en La Catedral,19,31
CELC_MVLL,Conversación en La Catedral,20,38
CELC_MVLL,Conversación en La Catedral,21,44
CELC_MVLL,Conversación en La Catedral,22,14
CELC_MVLL,Conversación en La Catedral,23,36
CELC_MVLL,Conversación en La Catedral,24,30
CELC_MVLL,Conversación en La Catedral,25,32
CELC_MVLL,Conversación en La Catedral,26,15
CELC_MVLL,Conversación en La Catedral,27,53
CELC_MVLL,Conversación en La Catedral,28,16
CELC_MVLL,Conversación en La Catedral,29,31
CELC_MVLL,Conversación en La Catedral,30,32
CELC_MVLL,Conversación en La Catedral,31,32
CELC_MVLL,Conversación en La Catedral,32,50
CELC_MVLL,Conversación en La Catedral,33,22
CELC_MVLL,Conversación en La Catedral,34,28
CELC_MVLL,Conversación en La Catedral,35,22
CELC_MVLL,Conversación en La Catedral,36,48
CELC_MVLL,Conversación en La Catedral,37,34
CELC_MVLL,Conversación en La Catedral,38,48
CELC_MVLL,Conversación en La Catedral,39,26
CELC_MVLL,Conversación en La Catedral,40,29
CELC_MVLL,Conversación en La Catedral,41,32
CELC_MVLL,Conversación en La Catedral,42,30
CELC_MVLL,Conversación en La Catedral,43,24
CELC_MVLL,Conversación en La Catedral,44,16
CELC_MVLL,Conversación en La Catedral,45,36
CELC_MVLL,Conversación en La Catedral,46,40
CELC_MVLL,Conversación en La Catedral,47,20
CELC_MVLL,Conversación en La Catedral,48,20
CELC_MVLL,Conversación en La Catedral,49,13
CELC_MVLL,Conversación en La Catedral,50,39

In [0]:
personajes_por_obra["densidad_narrativa"] = (
    personajes_por_obra["frecuencia"] /
    personajes_por_obra["bloques_distintos"]
).round(2)

for obra in personajes_por_obra["obra"].unique():

    data = (
        personajes_por_obra[
            personajes_por_obra["obra"] == obra
        ]
        .head(15)
        .sort_values("frecuencia", ascending=True)
    )

    fig = px.bar(
        data,
        x="frecuencia",
        y="entidad_canonica",
        orientation="h",
        text="frecuencia",
        title=f"Personajes o personas más mencionadas - {obra}",
        labels={
            "frecuencia": "Frecuencia",
            "entidad_canonica": "Personaje"
        },
        hover_data={
            "score_promedio": ':.4f',
            "bloques_distintos": True,
            "densidad_narrativa": ':.2f'
        },
        height=600
    )

    # Hover personalizado
    fig.update_traces(
        textposition="outside",
        hovertemplate=
        "<b>Personaje:</b> %{y}<br>" +
        "<b>Frecuencia:</b> %{x}<br>" +
        "<b>Score promedio:</b> %{customdata[0]:.4f}<br>" +
        "<b>Bloques distintos:</b> %{customdata[1]}<br>" +
        "<b>Densidad narrativa:</b> %{customdata[2]:.2f}<extra></extra>"
    )

    # Diseño visual
    fig.update_layout(
        title_x=0.5,
        template="plotly_white",
        yaxis=dict(categoryorder="total ascending")
    )

    fig.show()

# 14. Análisis de lugares y escenarios

Para aproximar la extracción de escenarios, se filtran las entidades de tipo `LOC`. En este contexto, los lugares permiten identificar espacios geográficos, escenarios narrativos o referencias territoriales presentes en cada obra.

Al igual que en personajes, se calculan frecuencia, score promedio y presencia en bloques distintos.

In [0]:
df_lugares = df_entidades_limpio[
    df_entidades_limpio["tipo"] == "LOC"
].copy()

display(df_lugares.head(10))

obra,titulo,autor,bloque_id,entidad,tipo,score,entidad_norm,entidad_canonica
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,La Catedral,LOC,0.9997674822807312,la catedral,La Catedral
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,La Crónica,LOC,0.9999179244041443,la crónica,La Crónica
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,avenida Tacna,LOC,0.9997281134128571,avenida tacna,avenida Tacna
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Perú,LOC,0.999950647354126,perú,Perú
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Colmena,LOC,0.9996123909950256,colmena,Colmena
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Plaza San Martín,LOC,0.9999350309371948,plaza san martín,Plaza San Martín
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Perú,LOC,0.9994574189186096,perú,Perú
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Hotel Crillón,LOC,0.9999241828918457,hotel crillón,Hotel Crillón
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Perú,LOC,0.9987001419067383,perú,Perú
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Miraflores,LOC,0.9999513626098633,miraflores,Miraflores

In [0]:
display(df_lugares[df_lugares['obra']=='CRDLI_IGDLV'].head(10))

obra,titulo,autor,bloque_id,entidad,tipo,score,entidad_norm,entidad_canonica
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,1,Perú,LOC,0.9999271631240845,perú,Perú
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,1,Victoria,LOC,0.6841578483581543,victoria,Victoria
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,1,Cozco,LOC,0.9997289776802063,cozco,Cozco
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,1,Charcas,LOC,0.7866821885108948,charcas,Charcas
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,1,Chichas,LOC,0.9985367059707642,chichas,Chichas
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,1,cabo de Pasau,LOC,0.9043872356414795,cabo de pasau,cabo de Pasau
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,2,Perú,LOC,0.9999754428863525,perú,Perú
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,2,Perú,LOC,0.9999603033065796,perú,Perú
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,3,Perú,LOC,0.9999743700027466,perú,Perú
CRDLI_IGDLV,Comentarios reales de los incas,Inca Garcilaso de la Vega,3,Huelva,LOC,0.9998886585235596,huelva,Huelva

In [0]:
lugares_por_obra = (
    df_lugares
    .groupby(["obra", "entidad_norm"])
    .agg(
        frecuencia=("entidad_norm", "count"),
        score_promedio=("score", "mean"),
        bloques_distintos=("bloque_id", "nunique")
    )
    .reset_index()
    .sort_values(["obra", "frecuencia"], ascending=[True, False])
)

lugares_por_obra["score_promedio"] = lugares_por_obra["score_promedio"].round(4)

display(lugares_por_obra.head(10))

obra,entidad_norm,frecuencia,score_promedio,bloques_distintos
CELC_MVLL,lima,107,0.9998,77
CELC_MVLL,arequipa,58,0.9982,31
CELC_MVLL,perú,49,0.9997,39
CELC_MVLL,pucallpa,49,0.9909,27
CELC_MVLL,san marcos,46,0.9704,26
CELC_MVLL,chincha,37,0.9994,20
CELC_MVLL,san miguel,27,0.993,25
CELC_MVLL,miraflores,26,0.9998,25
CELC_MVLL,ancón,24,0.983,11
CELC_MVLL,ica,23,0.9996,17

In [0]:
display(lugares_por_obra[lugares_por_obra['obra']=='CRDLI_IGDLV'].head(10))

obra,entidad_norm,frecuencia,score_promedio,bloques_distintos
CRDLI_IGDLV,perú,363,0.9968,188
CRDLI_IGDLV,cozco,354,0.9915,191
CRDLI_IGDLV,españa,163,0.9992,90
CRDLI_IGDLV,chili,54,0.9903,26
CRDLI_IGDLV,quitu,53,0.9999,32
CRDLI_IGDLV,antis,31,0.9211,23
CRDLI_IGDLV,indias,29,0.993,21
CRDLI_IGDLV,collasuyu,27,0.979,20
CRDLI_IGDLV,chincha,22,0.972,8
CRDLI_IGDLV,pachacámac,21,0.994,9

In [0]:
top_lugares_por_obra = (
    lugares_por_obra
    .groupby("obra", group_keys=False)
    .head(20)
)

display(top_lugares_por_obra)

obra,entidad_norm,frecuencia,score_promedio,bloques_distintos
CELC_MVLL,lima,107,0.9998,77
CELC_MVLL,arequipa,58,0.9982,31
CELC_MVLL,perú,49,0.9997,39
CELC_MVLL,pucallpa,49,0.9909,27
CELC_MVLL,san marcos,46,0.9704,26
CELC_MVLL,chincha,37,0.9994,20
CELC_MVLL,san miguel,27,0.993,25
CELC_MVLL,miraflores,26,0.9998,25
CELC_MVLL,ancón,24,0.983,11
CELC_MVLL,ica,23,0.9996,17
CELC_MVLL,plaza,20,0.9438,13
CELC_MVLL,palacio,18,0.999,11
CELC_MVLL,plaza de armas,18,0.9999,18
CELC_MVLL,colmena,16,0.9612,16
CELC_MVLL,tingo maría,16,0.9999,10
CELC_MVLL,cajamarca,15,0.9889,9
CELC_MVLL,la crónica,15,0.9842,15
CELC_MVLL,mirones,14,0.9793,11
CELC_MVLL,plaza san martín,14,0.9999,13
CELC_MVLL,méxico,13,0.9999,9
CRDLI_IGDLV,perú,363,0.9968,188
CRDLI_IGDLV,cozco,354,0.9915,191
CRDLI_IGDLV,españa,163,0.9992,90
CRDLI_IGDLV,chili,54,0.9903,26
CRDLI_IGDLV,quitu,53,0.9999,32
CRDLI_IGDLV,antis,31,0.9211,23
CRDLI_IGDLV,indias,29,0.993,21
CRDLI_IGDLV,collasuyu,27,0.979,20
CRDLI_IGDLV,chincha,22,0.972,8
CRDLI_IGDLV,pachacámac,21,0.994,9
CRDLI_IGDLV,rímac,20,0.999,12
CRDLI_IGDLV,chinchasuyu,19,0.9882,17
CRDLI_IGDLV,ciudad de los reyes,19,0.9905,15
CRDLI_IGDLV,panamá,18,1.0,11
CRDLI_IGDLV,sevilla,17,1.0,16
CRDLI_IGDLV,cuntisuyu,16,0.9798,13
CRDLI_IGDLV,arequepa,14,0.9977,7
CRDLI_IGDLV,collao,13,0.926,11
CRDLI_IGDLV,imperio,13,0.6549,13
CRDLI_IGDLV,méxico,13,0.9999,10

In [0]:
lugares_por_bloque = (
    df_lugares
    .groupby(["obra", "titulo", "bloque_id"])
    .size()
    .reset_index(name="cantidad_lugares")
    .sort_values(["obra", "bloque_id"])
)

display(lugares_por_bloque.head(50))

obra,titulo,bloque_id,cantidad_lugares
CELC_MVLL,Conversación en La Catedral,1,15
CELC_MVLL,Conversación en La Catedral,2,5
CELC_MVLL,Conversación en La Catedral,3,21
CELC_MVLL,Conversación en La Catedral,4,15
CELC_MVLL,Conversación en La Catedral,5,1
CELC_MVLL,Conversación en La Catedral,6,4
CELC_MVLL,Conversación en La Catedral,7,4
CELC_MVLL,Conversación en La Catedral,8,3
CELC_MVLL,Conversación en La Catedral,9,4
CELC_MVLL,Conversación en La Catedral,10,10
CELC_MVLL,Conversación en La Catedral,11,4
CELC_MVLL,Conversación en La Catedral,12,9
CELC_MVLL,Conversación en La Catedral,13,7
CELC_MVLL,Conversación en La Catedral,14,2
CELC_MVLL,Conversación en La Catedral,16,14
CELC_MVLL,Conversación en La Catedral,18,1
CELC_MVLL,Conversación en La Catedral,19,1
CELC_MVLL,Conversación en La Catedral,20,1
CELC_MVLL,Conversación en La Catedral,21,3
CELC_MVLL,Conversación en La Catedral,22,6
CELC_MVLL,Conversación en La Catedral,23,7
CELC_MVLL,Conversación en La Catedral,24,9
CELC_MVLL,Conversación en La Catedral,25,5
CELC_MVLL,Conversación en La Catedral,26,4
CELC_MVLL,Conversación en La Catedral,27,3
CELC_MVLL,Conversación en La Catedral,28,12
CELC_MVLL,Conversación en La Catedral,29,5
CELC_MVLL,Conversación en La Catedral,30,3
CELC_MVLL,Conversación en La Catedral,31,3
CELC_MVLL,Conversación en La Catedral,32,13
CELC_MVLL,Conversación en La Catedral,33,6
CELC_MVLL,Conversación en La Catedral,34,12
CELC_MVLL,Conversación en La Catedral,35,6
CELC_MVLL,Conversación en La Catedral,36,1
CELC_MVLL,Conversación en La Catedral,37,7
CELC_MVLL,Conversación en La Catedral,38,6
CELC_MVLL,Conversación en La Catedral,39,7
CELC_MVLL,Conversación en La Catedral,40,4
CELC_MVLL,Conversación en La Catedral,41,3
CELC_MVLL,Conversación en La Catedral,42,3
CELC_MVLL,Conversación en La Catedral,43,12
CELC_MVLL,Conversación en La Catedral,44,6
CELC_MVLL,Conversación en La Catedral,45,4
CELC_MVLL,Conversación en La Catedral,46,4
CELC_MVLL,Conversación en La Catedral,47,3
CELC_MVLL,Conversación en La Catedral,48,5
CELC_MVLL,Conversación en La Catedral,49,1
CELC_MVLL,Conversación en La Catedral,50,3
CELC_MVLL,Conversación en La Catedral,51,11
CELC_MVLL,Conversación en La Catedral,52,9

In [0]:
for obra in lugares_por_obra["obra"].unique():

    data = (
        lugares_por_obra[
            lugares_por_obra["obra"] == obra
        ]
        .head(15)
        .sort_values("frecuencia", ascending=True)
    )

    fig = px.bar(
        data,
        x="frecuencia",
        y="entidad_norm",
        orientation="h",
        text="frecuencia",
        title=f"Lugares o escenarios más mencionados - {obra}",
        labels={
            "frecuencia": "Frecuencia",
            "entidad_norm": "Lugar o escenario"
        },
        hover_data={
            "score_promedio": ':.4f',
            "bloques_distintos": True
        },
        height=600
    )

    # Hover personalizado
    fig.update_traces(
        textposition="outside",
        hovertemplate=
        "<b>Lugar:</b> %{y}<br>" +
        "<b>Frecuencia:</b> %{x}<br>" +
        "<b>Score promedio:</b> %{customdata[0]:.4f}<br>" +
        "<b>Bloques distintos:</b> %{customdata[1]}<extra></extra>"
    )

    # Diseño visual
    fig.update_layout(
        title_x=0.5,
        template="plotly_white",
        yaxis=dict(categoryorder="total ascending")
    )

    fig.show()

# 15. Construcción de redes de coocurrencia entre personajes

La red de coocurrencia conecta dos personajes cuando aparecen dentro del mismo bloque de texto. Cada nodo representa un personaje y cada arista representa una relación de aparición conjunta.

El peso de la arista indica cuántas veces apareció ese par de personajes en los mismos bloques. Para reducir ruido, se filtran relaciones con peso menor al umbral definido en `MIN_PESO_RED`.

In [0]:
df_red_personajes = df_personajes[
    ["obra", "titulo", "bloque_id", "entidad_canonica"]
].drop_duplicates()

display(df_red_personajes.head())

obra,titulo,bloque_id,entidad_canonica
CELC_MVLL,Conversación en La Catedral,1,Mario Vargas Llosa
CELC_MVLL,Conversación en La Catedral,1,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,1,Wilson
CELC_MVLL,Conversación en La Catedral,1,Carlitos
CELC_MVLL,Conversación en La Catedral,1,Norwin

In [0]:
personajes_agrupados_bloque = (
    df_red_personajes
    .groupby(["obra", "titulo", "bloque_id"])["entidad_canonica"]
    .apply(lambda x: sorted(set(x)))
    .reset_index(name="personajes")
)

personajes_agrupados_bloque["cantidad_personajes"] = personajes_agrupados_bloque["personajes"].apply(len)

display(personajes_agrupados_bloque.head(10))

obra,titulo,bloque_id,personajes,cantidad_personajes
CELC_MVLL,Conversación en La Catedral,1,"List(Carlitos, Convéncete, Director, Mario Vargas Llosa, Norwin, Orgambide, Santiago Zavala, Wilson)",8
CELC_MVLL,Conversación en La Catedral,2,"List(Ana, Becerrita, Jesús Vásquez, Milton, Norwin, Santiago Zavala)",6
CELC_MVLL,Conversación en La Catedral,3,"List(Ana, Batuquito, Director, Huxley, Popeye Arévalo, Rififí, Río Grande, Santiago Zavala, Teté Zavala)",9
CELC_MVLL,Conversación en La Catedral,4,"List(Ana, Batuque, Santiago Zavala, Solórzano)",4
CELC_MVLL,Conversación en La Catedral,5,"List(Batuque, Batuquito, Pancras, Santiago Zavala)",4
CELC_MVLL,Conversación en La Catedral,6,"List(Ambrosio Pardo, Céspedes, Fermín Zavala, Pancras, Santiago Zavala, Zoila, don, señora)",8
CELC_MVLL,Conversación en La Catedral,7,"List(Ambrosio Pardo, Chispas Zavala, Santiago Zavala, Saturnina, Teté Zavala)",5
CELC_MVLL,Conversación en La Catedral,8,"List(Ambrosio Pardo, Batuque, Carlitos, Huxley, Santiago Zavala, Saturnina, Trastabillea)",7
CELC_MVLL,Conversación en La Catedral,9,"List(Ambrosio Pardo, Batuque, Musa, Santiago Zavala)",4
CELC_MVLL,Conversación en La Catedral,10,"List(Ana, Batuque, Batuquito, Carlitos, Huxley, Norwin, Santiago Zavala)",7

In [0]:
bloques_con_coocurrencia = personajes_agrupados_bloque[
    personajes_agrupados_bloque["cantidad_personajes"] >= 2
].copy()

display(bloques_con_coocurrencia.head())

obra,titulo,bloque_id,personajes,cantidad_personajes
CELC_MVLL,Conversación en La Catedral,1,"List(Carlitos, Convéncete, Director, Mario Vargas Llosa, Norwin, Orgambide, Santiago Zavala, Wilson)",8
CELC_MVLL,Conversación en La Catedral,2,"List(Ana, Becerrita, Jesús Vásquez, Milton, Norwin, Santiago Zavala)",6
CELC_MVLL,Conversación en La Catedral,3,"List(Ana, Batuquito, Director, Huxley, Popeye Arévalo, Rififí, Río Grande, Santiago Zavala, Teté Zavala)",9
CELC_MVLL,Conversación en La Catedral,4,"List(Ana, Batuque, Santiago Zavala, Solórzano)",4
CELC_MVLL,Conversación en La Catedral,5,"List(Batuque, Batuquito, Pancras, Santiago Zavala)",4

In [0]:
from itertools import combinations

registros_coocurrencia = []

for _, row in bloques_con_coocurrencia.iterrows():
    obra = row["obra"]
    titulo = row["titulo"]
    bloque_id = row["bloque_id"]
    personajes = row["personajes"]

    for p1, p2 in combinations(personajes, 2):
        registros_coocurrencia.append({
            "obra": obra,
            "titulo": titulo,
            "bloque_id": bloque_id,
            "personaje_1": p1,
            "personaje_2": p2
        })

df_coocurrencia = pd.DataFrame(registros_coocurrencia)

display(df_coocurrencia.head(50))

obra,titulo,bloque_id,personaje_1,personaje_2
CELC_MVLL,Conversación en La Catedral,1,Carlitos,Convéncete
CELC_MVLL,Conversación en La Catedral,1,Carlitos,Director
CELC_MVLL,Conversación en La Catedral,1,Carlitos,Mario Vargas Llosa
CELC_MVLL,Conversación en La Catedral,1,Carlitos,Norwin
CELC_MVLL,Conversación en La Catedral,1,Carlitos,Orgambide
CELC_MVLL,Conversación en La Catedral,1,Carlitos,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,1,Carlitos,Wilson
CELC_MVLL,Conversación en La Catedral,1,Convéncete,Director
CELC_MVLL,Conversación en La Catedral,1,Convéncete,Mario Vargas Llosa
CELC_MVLL,Conversación en La Catedral,1,Convéncete,Norwin
CELC_MVLL,Conversación en La Catedral,1,Convéncete,Orgambide
CELC_MVLL,Conversación en La Catedral,1,Convéncete,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,1,Convéncete,Wilson
CELC_MVLL,Conversación en La Catedral,1,Director,Mario Vargas Llosa
CELC_MVLL,Conversación en La Catedral,1,Director,Norwin
CELC_MVLL,Conversación en La Catedral,1,Director,Orgambide
CELC_MVLL,Conversación en La Catedral,1,Director,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,1,Director,Wilson
CELC_MVLL,Conversación en La Catedral,1,Mario Vargas Llosa,Norwin
CELC_MVLL,Conversación en La Catedral,1,Mario Vargas Llosa,Orgambide
CELC_MVLL,Conversación en La Catedral,1,Mario Vargas Llosa,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,1,Mario Vargas Llosa,Wilson
CELC_MVLL,Conversación en La Catedral,1,Norwin,Orgambide
CELC_MVLL,Conversación en La Catedral,1,Norwin,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,1,Norwin,Wilson
CELC_MVLL,Conversación en La Catedral,1,Orgambide,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,1,Orgambide,Wilson
CELC_MVLL,Conversación en La Catedral,1,Santiago Zavala,Wilson
CELC_MVLL,Conversación en La Catedral,2,Ana,Becerrita
CELC_MVLL,Conversación en La Catedral,2,Ana,Jesús Vásquez
CELC_MVLL,Conversación en La Catedral,2,Ana,Milton
CELC_MVLL,Conversación en La Catedral,2,Ana,Norwin
CELC_MVLL,Conversación en La Catedral,2,Ana,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,2,Becerrita,Jesús Vásquez
CELC_MVLL,Conversación en La Catedral,2,Becerrita,Milton
CELC_MVLL,Conversación en La Catedral,2,Becerrita,Norwin
CELC_MVLL,Conversación en La Catedral,2,Becerrita,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,2,Jesús Vásquez,Milton
CELC_MVLL,Conversación en La Catedral,2,Jesús Vásquez,Norwin
CELC_MVLL,Conversación en La Catedral,2,Jesús Vásquez,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,2,Milton,Norwin
CELC_MVLL,Conversación en La Catedral,2,Milton,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,2,Norwin,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,3,Ana,Batuquito
CELC_MVLL,Conversación en La Catedral,3,Ana,Director
CELC_MVLL,Conversación en La Catedral,3,Ana,Huxley
CELC_MVLL,Conversación en La Catedral,3,Ana,Popeye Arévalo
CELC_MVLL,Conversación en La Catedral,3,Ana,Rififí
CELC_MVLL,Conversación en La Catedral,3,Ana,Río Grande
CELC_MVLL,Conversación en La Catedral,3,Ana,Santiago Zavala

In [0]:
if len(df_coocurrencia) > 0:
    red_coocurrencia = (
        df_coocurrencia
        .groupby(["obra", "personaje_1", "personaje_2"])
        .size()
        .reset_index(name="peso")
        .sort_values(["obra", "peso"], ascending=[True, False])
    )

    display(red_coocurrencia.head(50))
else:
    print("No se encontraron coocurrencias entre personajes.")
    red_coocurrencia = pd.DataFrame(
        columns=["obra", "personaje_1", "personaje_2", "peso"]
    )

obra,personaje_1,personaje_2,peso
CELC_MVLL,Ambrosio Pardo,Santiago Zavala,104
CELC_MVLL,Ambrosio Pardo,Cayo Bermúdez,83
CELC_MVLL,Ambrosio Pardo,Fermín Zavala,76
CELC_MVLL,Carlitos,Santiago Zavala,72
CELC_MVLL,Amalia Landa,Ambrosio Pardo,70
CELC_MVLL,Fermín Zavala,Santiago Zavala,61
CELC_MVLL,Chispas Zavala,Santiago Zavala,60
CELC_MVLL,Santiago Zavala,Teté Zavala,60
CELC_MVLL,Ambrosio Pardo,don,59
CELC_MVLL,Fermín Zavala,don,58
CELC_MVLL,Ambrosio Pardo,Ludovico,54
CELC_MVLL,Cayo Bermúdez,Ludovico,54
CELC_MVLL,Cayo Bermúdez,Santiago Zavala,52
CELC_MVLL,Cayo Bermúdez,Fermín Zavala,50
CELC_MVLL,Chispas Zavala,Teté Zavala,48
CELC_MVLL,Ambrosio Pardo,Queta,47
CELC_MVLL,Hipólito,Ludovico,45
CELC_MVLL,Cayo Bermúdez,Coronel Lozano,42
CELC_MVLL,Cayo Bermúdez,Presidente,42
CELC_MVLL,Hortensia,Queta,42
CELC_MVLL,Cayo Bermúdez,Queta,41
CELC_MVLL,Cayo Bermúdez,don,40
CELC_MVLL,Santiago Zavala,don,40
CELC_MVLL,Popeye Arévalo,Santiago Zavala,39
CELC_MVLL,Ambrosio Pardo,Chispas Zavala,38
CELC_MVLL,Cayo Bermúdez,Hipólito,38
CELC_MVLL,Cayo Bermúdez,Odría,38
CELC_MVLL,Ambrosio Pardo,Teté Zavala,37
CELC_MVLL,Cayo Bermúdez,Espina,37
CELC_MVLL,Amalia Landa,Fermín Zavala,36
CELC_MVLL,Amalia Landa,Queta,36
CELC_MVLL,Ambrosio Pardo,Odría,36
CELC_MVLL,Aída,Santiago Zavala,36
CELC_MVLL,Amalia Landa,Santiago Zavala,35
CELC_MVLL,Ambrosio Pardo,Carlitos,35
CELC_MVLL,Ambrosio Pardo,Hipólito,33
CELC_MVLL,Chispas Zavala,Fermín Zavala,33
CELC_MVLL,Coronel Lozano,Ludovico,33
CELC_MVLL,Santiago Zavala,Zoila,33
CELC_MVLL,Cayo Bermúdez,Trifulcio,31
CELC_MVLL,Cayo Bermúdez,Hortensia,30
CELC_MVLL,Odría,Santiago Zavala,30
CELC_MVLL,Amalia Landa,Hortensia,29
CELC_MVLL,Aída,Jacobo,29
CELC_MVLL,Fermín Zavala,Teté Zavala,29
CELC_MVLL,Ambrosio Pardo,Popeye Arévalo,28
CELC_MVLL,Ambrosio Pardo,Trifulcio,28
CELC_MVLL,Cayo Bermúdez,Landa,28
CELC_MVLL,Coronel Lozano,Hipólito,28
CELC_MVLL,Jacobo,Santiago Zavala,28

In [0]:
red_coocurrencia_filtrada = red_coocurrencia[
    red_coocurrencia["peso"] >= MIN_PESO_RED
].copy()

display(red_coocurrencia_filtrada.head(50))

obra,personaje_1,personaje_2,peso
CELC_MVLL,Ambrosio Pardo,Santiago Zavala,104
CELC_MVLL,Ambrosio Pardo,Cayo Bermúdez,83
CELC_MVLL,Ambrosio Pardo,Fermín Zavala,76
CELC_MVLL,Carlitos,Santiago Zavala,72
CELC_MVLL,Amalia Landa,Ambrosio Pardo,70
CELC_MVLL,Fermín Zavala,Santiago Zavala,61
CELC_MVLL,Chispas Zavala,Santiago Zavala,60
CELC_MVLL,Santiago Zavala,Teté Zavala,60
CELC_MVLL,Ambrosio Pardo,don,59
CELC_MVLL,Fermín Zavala,don,58
CELC_MVLL,Ambrosio Pardo,Ludovico,54
CELC_MVLL,Cayo Bermúdez,Ludovico,54
CELC_MVLL,Cayo Bermúdez,Santiago Zavala,52
CELC_MVLL,Cayo Bermúdez,Fermín Zavala,50
CELC_MVLL,Chispas Zavala,Teté Zavala,48
CELC_MVLL,Ambrosio Pardo,Queta,47
CELC_MVLL,Hipólito,Ludovico,45
CELC_MVLL,Cayo Bermúdez,Coronel Lozano,42
CELC_MVLL,Cayo Bermúdez,Presidente,42
CELC_MVLL,Hortensia,Queta,42
CELC_MVLL,Cayo Bermúdez,Queta,41
CELC_MVLL,Cayo Bermúdez,don,40
CELC_MVLL,Santiago Zavala,don,40
CELC_MVLL,Popeye Arévalo,Santiago Zavala,39
CELC_MVLL,Ambrosio Pardo,Chispas Zavala,38
CELC_MVLL,Cayo Bermúdez,Hipólito,38
CELC_MVLL,Cayo Bermúdez,Odría,38
CELC_MVLL,Ambrosio Pardo,Teté Zavala,37
CELC_MVLL,Cayo Bermúdez,Espina,37
CELC_MVLL,Amalia Landa,Fermín Zavala,36
CELC_MVLL,Amalia Landa,Queta,36
CELC_MVLL,Ambrosio Pardo,Odría,36
CELC_MVLL,Aída,Santiago Zavala,36
CELC_MVLL,Amalia Landa,Santiago Zavala,35
CELC_MVLL,Ambrosio Pardo,Carlitos,35
CELC_MVLL,Ambrosio Pardo,Hipólito,33
CELC_MVLL,Chispas Zavala,Fermín Zavala,33
CELC_MVLL,Coronel Lozano,Ludovico,33
CELC_MVLL,Santiago Zavala,Zoila,33
CELC_MVLL,Cayo Bermúdez,Trifulcio,31
CELC_MVLL,Cayo Bermúdez,Hortensia,30
CELC_MVLL,Odría,Santiago Zavala,30
CELC_MVLL,Amalia Landa,Hortensia,29
CELC_MVLL,Aída,Jacobo,29
CELC_MVLL,Fermín Zavala,Teté Zavala,29
CELC_MVLL,Ambrosio Pardo,Popeye Arévalo,28
CELC_MVLL,Ambrosio Pardo,Trifulcio,28
CELC_MVLL,Cayo Bermúdez,Landa,28
CELC_MVLL,Coronel Lozano,Hipólito,28
CELC_MVLL,Jacobo,Santiago Zavala,28

In [0]:
grafos_por_obra = {}

for obra in red_coocurrencia_filtrada["obra"].unique():
    data_obra = red_coocurrencia_filtrada[
        red_coocurrencia_filtrada["obra"] == obra
    ]

    G = nx.Graph()

    for _, row in data_obra.iterrows():
        G.add_edge(
            row["personaje_1"],
            row["personaje_2"],
            weight=row["peso"],
            distance=1/row["peso"]
        )

    grafos_por_obra[obra] = G

    print(f"Obra: {obra}")
    print("Nodos:", G.number_of_nodes())
    print("Aristas:", G.number_of_edges())
    print("-" * 50)

Obra: CELC_MVLL
Nodos: 206
Aristas: 2103
--------------------------------------------------
Obra: CRDLI_IGDLV
Nodos: 174
Aristas: 715
--------------------------------------------------

# 16. Métricas de centralidad de la red

Una vez construida la red, se calculan métricas para identificar personajes estructuralmente importantes:

- **Grado de centralidad:** mide cuántas conexiones tiene un personaje respecto al total posible.
- **Intermediación:** identifica personajes que funcionan como puentes dentro de la red.
- **Cercanía:** estima qué tan cerca está un personaje del resto de la red.
- **Peso total de relaciones:** suma la intensidad de todas sus coocurrencias.

In [0]:
registros_centralidad = []

for obra, G in grafos_por_obra.items():

    grado_centralidad = nx.degree_centrality(G)
    intermediacion = nx.betweenness_centrality(G, weight="weight")
    cercania = nx.closeness_centrality(G, distance="distance")

    for nodo in G.nodes():
        registros_centralidad.append({
            "obra": obra,
            "personaje": nodo,
            "grado_centralidad": grado_centralidad.get(nodo, 0),
            "intermediacion": intermediacion.get(nodo, 0),
            "cercania": cercania.get(nodo, 0),
            "grado": G.degree(nodo),
            "peso_total_relaciones": sum(
                data["weight"] for _, _, data in G.edges(nodo, data=True)
            )
        })

df_centralidad = pd.DataFrame(registros_centralidad)

df_centralidad["grado_centralidad"] = df_centralidad["grado_centralidad"].round(4)
df_centralidad["intermediacion"] = df_centralidad["intermediacion"].round(4)
df_centralidad["cercania"] = df_centralidad["cercania"].round(4)

display(df_centralidad.head(50))

obra,personaje,grado_centralidad,intermediacion,cercania,grado,peso_total_relaciones
CELC_MVLL,Ambrosio Pardo,0.761,0.1122,3.861,156,1637
CELC_MVLL,Santiago Zavala,0.639,0.099,3.8188,131,1359
CELC_MVLL,Cayo Bermúdez,0.6585,0.0875,3.8262,135,1360
CELC_MVLL,Fermín Zavala,0.5073,0.0416,3.7434,104,977
CELC_MVLL,Carlitos,0.3561,0.0379,3.6376,73,551
CELC_MVLL,Amalia Landa,0.4293,0.0792,3.7124,88,727
CELC_MVLL,Chispas Zavala,0.2732,0.04,3.5974,56,455
CELC_MVLL,Teté Zavala,0.2732,0.0248,3.5975,56,470
CELC_MVLL,don,0.4439,0.0317,3.6611,91,726
CELC_MVLL,Ludovico,0.4098,0.0436,3.6776,84,704
CELC_MVLL,Queta,0.3268,0.0286,3.638,67,557
CELC_MVLL,Hipólito,0.3073,0.0117,3.5421,63,499
CELC_MVLL,Coronel Lozano,0.3463,0.0251,3.5321,71,467
CELC_MVLL,Presidente,0.3463,0.0253,3.537,71,462
CELC_MVLL,Hortensia,0.2683,0.0139,3.4853,55,383
CELC_MVLL,Popeye Arévalo,0.3268,0.022,3.5086,67,498
CELC_MVLL,Odría,0.3463,0.0352,3.5654,71,507
CELC_MVLL,Espina,0.3171,0.0235,3.4855,65,381
CELC_MVLL,Aída,0.1659,0.0102,3.4805,34,278
CELC_MVLL,Zoila,0.1854,0.014,3.4284,38,285
CELC_MVLL,Trifulcio,0.2634,0.0168,3.483,54,403
CELC_MVLL,Jacobo,0.1415,0.0087,3.3795,29,225
CELC_MVLL,Landa,0.3024,0.0179,3.3992,62,361
CELC_MVLL,Becerrita,0.161,0.013,3.3627,33,213
CELC_MVLL,Carlota,0.1805,0.0104,3.2661,37,218
CELC_MVLL,Ana,0.1707,0.0163,3.3347,35,168
CELC_MVLL,Trinidad,0.2146,0.0102,3.3273,44,225
CELC_MVLL,Ivonne,0.1707,0.0049,3.169,35,215
CELC_MVLL,Periquito,0.1415,0.0045,3.2717,29,182
CELC_MVLL,Símula,0.1659,0.0087,3.1608,34,178
CELC_MVLL,Paredes,0.2341,0.0159,3.2602,48,241
CELC_MVLL,Quetita,0.1268,0.0036,3.0842,26,140
CELC_MVLL,Alcibíades,0.1756,0.0011,3.1875,36,173
CELC_MVLL,General,0.2098,0.0035,3.201,43,234
CELC_MVLL,Serrano,0.2049,0.0148,3.1936,42,187
CELC_MVLL,Solórzano,0.1463,0.0079,3.1835,30,157
CELC_MVLL,Norwin,0.1268,0.0067,3.1672,26,124
CELC_MVLL,Molina,0.1659,0.0013,3.1445,34,202
CELC_MVLL,Héctor,0.1122,0.0034,3.1339,23,143
CELC_MVLL,Robertito,0.1171,0.0062,3.0048,24,125
CELC_MVLL,Amalita Hortensia,0.1171,0.0077,3.1361,24,113
CELC_MVLL,Arispe,0.1171,0.0054,3.093,24,125
CELC_MVLL,Téllez,0.1902,0.0123,3.1145,39,231
CELC_MVLL,Washington,0.122,0.0046,3.1002,25,139
CELC_MVLL,Musa,0.1561,0.0063,3.1236,32,156
CELC_MVLL,Zavala,0.2,0.0129,3.0699,41,169
CELC_MVLL,Gertrudis,0.1024,0.002,2.9462,21,106
CELC_MVLL,Don,0.1659,0.0143,3.0315,34,149
CELC_MVLL,Hilario,0.0976,0.0026,3.0446,20,104
CELC_MVLL,Arbeláez,0.161,0.0069,3.0178,33,144

In [0]:
top_grado_centralidad = (
    df_centralidad
    .sort_values(["obra", "grado_centralidad"], ascending=[True, False])
    .groupby("obra", group_keys=False)
    .head(10)
)

display(top_grado_centralidad)

obra,personaje,grado_centralidad,intermediacion,cercania,grado,peso_total_relaciones
CELC_MVLL,Ambrosio Pardo,0.761,0.1122,3.861,156,1637
CELC_MVLL,Cayo Bermúdez,0.6585,0.0875,3.8262,135,1360
CELC_MVLL,Santiago Zavala,0.639,0.099,3.8188,131,1359
CELC_MVLL,Fermín Zavala,0.5073,0.0416,3.7434,104,977
CELC_MVLL,don,0.4439,0.0317,3.6611,91,726
CELC_MVLL,Amalia Landa,0.4293,0.0792,3.7124,88,727
CELC_MVLL,Ludovico,0.4098,0.0436,3.6776,84,704
CELC_MVLL,Carlitos,0.3561,0.0379,3.6376,73,551
CELC_MVLL,Coronel Lozano,0.3463,0.0251,3.5321,71,467
CELC_MVLL,Presidente,0.3463,0.0253,3.537,71,462
CRDLI_IGDLV,Inca,0.7572,0.3312,2.7238,131,937
CRDLI_IGDLV,Rey,0.5896,0.1596,2.6889,102,667
CRDLI_IGDLV,Reyes,0.4855,0.1107,2.6772,84,583
CRDLI_IGDLV,Incas,0.3064,0.059,2.6138,53,321
CRDLI_IGDLV,Huayna Cápac,0.2659,0.0654,2.5276,46,235
CRDLI_IGDLV,Atahuallpa,0.2601,0.0699,2.4559,45,218
CRDLI_IGDLV,Sol,0.2486,0.0642,2.6016,43,255
CRDLI_IGDLV,Reyes Incas,0.2023,0.0212,2.5112,35,206
CRDLI_IGDLV,Príncipe,0.185,0.0276,2.4922,32,157
CRDLI_IGDLV,Inca Manco Cápac,0.1329,0.0103,2.3783,23,119

In [0]:
top_intermediacion = (
    df_centralidad
    .sort_values(["obra", "intermediacion"], ascending=[True, False])
    .groupby("obra", group_keys=False)
    .head(10)
)

display(top_intermediacion)

obra,personaje,grado_centralidad,intermediacion,cercania,grado,peso_total_relaciones
CELC_MVLL,Ambrosio Pardo,0.761,0.1122,3.861,156,1637
CELC_MVLL,Santiago Zavala,0.639,0.099,3.8188,131,1359
CELC_MVLL,Cayo Bermúdez,0.6585,0.0875,3.8262,135,1360
CELC_MVLL,Amalia Landa,0.4293,0.0792,3.7124,88,727
CELC_MVLL,Ludovico,0.4098,0.0436,3.6776,84,704
CELC_MVLL,Fermín Zavala,0.5073,0.0416,3.7434,104,977
CELC_MVLL,Chispas Zavala,0.2732,0.04,3.5974,56,455
CELC_MVLL,Carlitos,0.3561,0.0379,3.6376,73,551
CELC_MVLL,Odría,0.3463,0.0352,3.5654,71,507
CELC_MVLL,don,0.4439,0.0317,3.6611,91,726
CRDLI_IGDLV,Inca,0.7572,0.3312,2.7238,131,937
CRDLI_IGDLV,Rey,0.5896,0.1596,2.6889,102,667
CRDLI_IGDLV,Reyes,0.4855,0.1107,2.6772,84,583
CRDLI_IGDLV,Atahuallpa,0.2601,0.0699,2.4559,45,218
CRDLI_IGDLV,Huayna Cápac,0.2659,0.0654,2.5276,46,235
CRDLI_IGDLV,Sol,0.2486,0.0642,2.6016,43,255
CRDLI_IGDLV,Incas,0.3064,0.059,2.6138,53,321
CRDLI_IGDLV,Príncipe,0.185,0.0276,2.4922,32,157
CRDLI_IGDLV,Pachacámac,0.0751,0.0216,2.0888,13,44
CRDLI_IGDLV,Reyes Incas,0.2023,0.0212,2.5112,35,206

In [0]:
top_peso_relaciones = (
    df_centralidad
    .sort_values(["obra", "peso_total_relaciones"], ascending=[True, False])
    .groupby("obra", group_keys=False)
    .head(10)
)

display(top_peso_relaciones)

obra,personaje,grado_centralidad,intermediacion,cercania,grado,peso_total_relaciones
CELC_MVLL,Ambrosio Pardo,0.761,0.1122,3.861,156,1637
CELC_MVLL,Cayo Bermúdez,0.6585,0.0875,3.8262,135,1360
CELC_MVLL,Santiago Zavala,0.639,0.099,3.8188,131,1359
CELC_MVLL,Fermín Zavala,0.5073,0.0416,3.7434,104,977
CELC_MVLL,Amalia Landa,0.4293,0.0792,3.7124,88,727
CELC_MVLL,don,0.4439,0.0317,3.6611,91,726
CELC_MVLL,Ludovico,0.4098,0.0436,3.6776,84,704
CELC_MVLL,Queta,0.3268,0.0286,3.638,67,557
CELC_MVLL,Carlitos,0.3561,0.0379,3.6376,73,551
CELC_MVLL,Odría,0.3463,0.0352,3.5654,71,507
CRDLI_IGDLV,Inca,0.7572,0.3312,2.7238,131,937
CRDLI_IGDLV,Rey,0.5896,0.1596,2.6889,102,667
CRDLI_IGDLV,Reyes,0.4855,0.1107,2.6772,84,583
CRDLI_IGDLV,Incas,0.3064,0.059,2.6138,53,321
CRDLI_IGDLV,Sol,0.2486,0.0642,2.6016,43,255
CRDLI_IGDLV,Huayna Cápac,0.2659,0.0654,2.5276,46,235
CRDLI_IGDLV,Atahuallpa,0.2601,0.0699,2.4559,45,218
CRDLI_IGDLV,Reyes Incas,0.2023,0.0212,2.5112,35,206
CRDLI_IGDLV,Príncipe,0.185,0.0276,2.4922,32,157
CRDLI_IGDLV,Inca Manco Cápac,0.1329,0.0103,2.3783,23,119

In [0]:
for obra in df_centralidad["obra"].unique():

    data = (
        df_centralidad[
            df_centralidad["obra"] == obra
        ]
        .sort_values("grado_centralidad", ascending=False)
        .head(15)
        .sort_values("grado_centralidad", ascending=True)
    )

    fig = px.bar(
        data,
        x="grado_centralidad",
        y="personaje",
        orientation="h",
        text="grado_centralidad",
        title=f"Personajes con mayor grado de centralidad - {obra}",
        labels={
            "grado_centralidad": "Grado de centralidad",
            "personaje": "Personaje"
        },
        hover_data={
            "intermediacion": ':.4f',
            "cercania": ':.4f',
            "grado": True,
            "peso_total_relaciones": ':.2f'
        },
        height=650
    )

    fig.update_traces(
        texttemplate="%{text:.4f}",
        textposition="outside",
        hovertemplate=
        "<b>Personaje:</b> %{y}<br>" +
        "<b>Grado centralidad:</b> %{x:.4f}<br>" +
        "<b>Intermediación:</b> %{customdata[0]:.4f}<br>" +
        "<b>Cercanía:</b> %{customdata[1]:.4f}<br>" +
        "<b>Grado:</b> %{customdata[2]}<br>" +
        "<b>Peso total relaciones:</b> %{customdata[3]:.2f}<extra></extra>"
    )

    fig.update_layout(
        title_x=0.5,
        template="plotly_white",
        yaxis=dict(categoryorder="total ascending")
    )

    fig.show()

Que Conversación en La Catedral dé a `Ambrosio Pardo` como el nodo con mayor centralidad **NO** significa automáticamente que sea:

- el protagonista;
- el personaje principal;
- el más importante narrativamente.

Y de hecho, en análisis de redes narrativas esto es completamente normal.

    Importante: Las métricas de centralidad NO miden: protagonismo literario, miden: posición estructural dentro de la red.

**¿Qué significa entonces que Ambrosio Pardo tenga alta centralidad?**

Probablemente significa que:

- conecta múltiples grupos de personajes;
- aparece junto a muchos personajes distintos;
- sirve como puente narrativo;
- participa en varias tramas;
- tiene alta coocurrencia.

Y eso encaja MUCHO con la novela.


**Mario Vargas Llosa** construye una narrativa muy fragmentada y coral.

Entonces:

* Santiago Zavala puede ser el eje psicológico;
* PERO Ambrosio puede funcionar como:
    - conector social;
    - puente político;
    - articulador de recuerdos;
    - vínculo entre clases sociales;
    - nexo entre líneas narrativas.


                                                    centralidad ≠ protagonismo

# 17. Visualización interactiva con PyVis

PyVis permite exportar las redes de personajes como archivos HTML interactivos. Los HTML se guardan dentro del volumen de Databricks, en la subcarpeta `grafos`.

In [0]:
# descomentamos si no se instalo antes

#%pip install pyvis

com.databricks.backend.common.rpc.CommandSkippedException
	at com.databricks.spark.chauffeur.SequenceExecutionState.$anonfun$cancel$3(SequenceExecutionState.scala:141)
	at com.databricks.spark.chauffeur.SequenceExecutionState.$anonfun$cancel$3$adapted(SequenceExecutionState.scala:136)
	at scala.collection.immutable.Range.foreach(Range.scala:192)
	at com.databricks.spark.chauffeur.SequenceExecutionState.cancel(SequenceExecutionState.scala:136)
	at com.databricks.spark.chauffeur.ExecContextState.cancelRunningSequence(ExecContextState.scala:725)
	at com.databricks.spark.chauffeur.ExecContextState.$anonfun$cancel$1(ExecContextState.scala:443)
	at scala.Option.getOrElse(Option.scala:201)
	at com.databricks.spark.chauffeur.ExecContextState.cancel(ExecContextState.scala:443)
	at com.databricks.spark.chauffeur.ExecutionContextManagerV1.cancelExecution(ExecutionContextManagerV1.scala:503)
	at com.databricks.spark.chauffeur.ChauffeurState.$anonfun$process$1(ChauffeurState.scala:794)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperation$1(UsageLogging.scala:531)
	at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:669)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$6(UsageLogging.scala:696)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.spark.chauffeur.ChauffeurState.withAttributionContext(ChauffeurState.scala:74)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags(AttributionContextTracing.scala:201)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags$(AttributionContextTracing.scala:182)
	at com.databricks.spark.chauffeur.ChauffeurState.withAttributionTags(ChauffeurState.scala:74)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$5(UsageLogging.scala:664)
	at com.databricks.logging.UsageLogging.withOtelSpanInContext$1(UsageLogging.scala:656)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:659)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:540)
	at com.databricks.spark.chauffeur.ChauffeurState.recordOperationWithResultTags(ChauffeurState.scala:74)
	at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:532)
	at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:496)
	at com.databricks.spark.chauffeur.ChauffeurState.recordOperation(ChauffeurState.scala:74)
	at com.databricks.spark.chauffeur.ChauffeurState.process(ChauffeurState.scala:766)
	at com.databricks.spark.chauffeur.Chauffeur.handleDriverRequest$1(Chauffeur.scala:842)
	at com.databricks.spark.chauffeur.Chauffeur.$anonfun$handleDriverRequests$2(Chauffeur.scala:869)
	at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:669)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$6(UsageLogging.scala:696)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.spark.chauffeur.Chauffeur.withAttributionContext(Chauffeur.scala:145)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags(AttributionContextTracing.scala:201)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags$(AttributionContextTracing.scala:182)
	at com.databricks.spark.chauffeur.Chauffeur.withAttributionTags(Chauffeur.scala:145)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$5(UsageLogging.scala:664)
	at com.databricks.logging.UsageLogging.withOtelSpanInContext$1(UsageLogging.scala:656)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:659)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:540)
	at com.databricks.spark.chauffeur.Chauffeur.recordOperationWithResultTags(Chauffeur.scala:145)
	at com.databricks.spark.chauffeur.Chauffeur.handleDriverRequestWithUsageLogging$1(Chauffeur.scala:868)
	at com.databricks.spark.chauffeur.Chauffeur.handleDriverRequests(Chauffeur.scala:919)
	at com.databricks.spark.chauffeur.ChauffeurCompatServerBackend.$anonfun$new$17(ChauffeurCompatServerBackend.scala:208)
	at com.databricks.spark.chauffeur.ChauffeurCompatServerBackend.$anonfun$new$17$adapted(ChauffeurCompatServerBackend.scala:207)
	at com.databricks.rpc.armeria.UnaryRpcHandler$.$anonfun$legacyWithRPCContext$1(UnaryRpcHandler.scala:517)
	at com.databricks.rpc.armeria.UnaryRpcHandler.$anonfun$callFunc$2(UnaryRpcHandler.scala:319)
	at com.databricks.rpc.armeria.Util$.handleUnexpectedExceptions(Util.scala:87)
	at com.databricks.rpc.armeria.UnaryRpcHandler.callFunc(UnaryRpcHandler.scala:319)
	at com.databricks.rpc.armeria.UnaryRpcHandlerInternal.callFuncWithHooks(UnaryRpcHandler.scala:647)
	at com.databricks.rpc.armeria.UnaryRpcHandlerInternal.$anonfun$callFunc$3(UnaryRpcHandler.scala:625)
	at com.databricks.rpc.OperationSpan.$anonfun$wrapFuture$1(OperationSpan.scala:69)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.rpc.OperationSpan.withAttributionContext(OperationSpan.scala:22)
	at com.databricks.rpc.OperationSpan.wrapFuture(OperationSpan.scala:68)
	at com.databricks.rpc.armeria.UnaryRpcHandlerInternal.callFunc(UnaryRpcHandler.scala:623)
	at com.databricks.rpc.armeria.UnaryRpcHandler.$anonfun$handleRpc0$3(UnaryRpcHandler.scala:276)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.rpc.armeria.UnaryRpcHandler.withAttributionContext(UnaryRpcHandler.scala:43)
	at com.databricks.rpc.armeria.UnaryRpcHandler.$anonfun$handleRpc0$2(UnaryRpcHandler.scala:236)
	at com.databricks.context.integrity.IntegrityCheckContext$ThreadLocalStorage$.withValue(IntegrityCheckContext.scala:76)
	at com.databricks.rpc.armeria.UnaryRpcHandler.handleRpc0(UnaryRpcHandler.scala:236)
	at com.databricks.rpc.armeria.UnaryRpcHandler.$anonfun$handleRpc$1(UnaryRpcHandler.scala:207)
	at com.databricks.rpc.armeria.server.internal.RequestCompletionTracker.wrap(RequestCompletionTracker.scala:184)
	at com.databricks.rpc.armeria.UnaryRpcHandler.handleRpc(UnaryRpcHandler.scala:207)
	at com.databricks.rpc.armeria.UnaryRpcHandler.handleJettyRpc(UnaryRpcHandler.scala:88)
	at com.databricks.rpc.armeria.UnaryRpcServiceInternal.handleJettyRpcWithAggregatedContent(UnaryRpcService.scala:528)
	at com.databricks.rpc.armeria.UnaryRpcServiceInternal.$anonfun$handleContextAwareJettyRpcWithAggregatedContent$2(UnaryRpcService.scala:439)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.rpc.armeria.UnaryRpcServiceInternal.withAttributionContext(UnaryRpcService.scala:189)
	at com.databricks.rpc.armeria.UnaryRpcServiceInternal.$anonfun$handleContextAwareJettyRpcWithAggregatedContent$1(UnaryRpcService.scala:434)
	at com.databricks.context.integrity.IntegrityCheckContext$ThreadLocalStorage$.withValue(IntegrityCheckContext.scala:76)
	at com.databricks.rpc.armeria.UnaryRpcServiceInternal.handleContextAwareJettyRpcWithAggregatedContent(UnaryRpcService.scala:433)
	at com.databricks.rpc.armeria.UnaryRpcServiceInternal.$anonfun$handleJettyJsonRpc$2(UnaryRpcService.scala:413)
	at com.databricks.rpc.armeria.Util$.handleUnexpectedExceptions(Util.scala:87)
	at com.databricks.rpc.armeria.Util$.handleUnexpectedExceptions(Util.scala:111)
	at com.databricks.rpc.armeria.UnaryRpcServiceInternal.$anonfun$handleJettyJsonRpc$1(UnaryRpcService.scala:408)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:481)
	at com.databricks.threading.DatabricksExecutionContext$InstrumentedRunnable.run(DatabricksExecutionContext.scala:36)
	at grpc_shaded.com.linecorp.armeria.common.DefaultContextAwareRunnable.run(DefaultContextAwareRunnable.java:45)
	at com.databricks.threading.ContextBoundRunnable.$anonfun$run$2(ContextBoundRunnable.scala:16)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.threading.ContextBoundRunnable.withAttributionContext(ContextBoundRunnable.scala:7)
	at com.databricks.threading.ContextBoundRunnable.$anonfun$run$1(ContextBoundRunnable.scala:16)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.context.integrity.IntegrityCheckContext$ThreadLocalStorage$.withValue(IntegrityCheckContext.scala:76)
	at com.databricks.threading.ContextBoundRunnable.run(ContextBoundRunnable.scala:15)
	at com.databricks.threading.InstrumentedExecutorService.$anonfun$makeContextAware$2(InstrumentedExecutorService.scala:257)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.threading.InstrumentedExecutorService.$anonfun$instrumentationWrapper$1(InstrumentedExecutorService.scala:299)
	at com.databricks.instrumentation.QueuedThreadPoolInstrumenter.trackActiveThreads(QueuedThreadPoolInstrumenter.scala:132)
	at com.databricks.instrumentation.QueuedThreadPoolInstrumenter.trackActiveThreads$(QueuedThreadPoolInstrumenter.scala:129)
	at com.databricks.threading.InstrumentedExecutorService.trackActiveThreads(InstrumentedExecutorService.scala:72)
	at com.databricks.threading.InstrumentedExecutorService.instrumentationWrapper(InstrumentedExecutorService.scala:287)
	at com.databricks.threading.InstrumentedExecutorService.$anonfun$makeContextAware$1(InstrumentedExecutorService.scala:259)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

In [0]:
# Carpeta de salida para los grafos interactivos.
Path(RUTA_GRAFOS).mkdir(parents=True, exist_ok=True)

print("Carpeta de grafos creada o verificada:", RUTA_GRAFOS)

Carpeta de grafos creada o verificada: /Volumes/workspace/default/mi_volumen/proyecto_nlp_libros/grafos

In [0]:
archivos_grafos = []

for obra, G in grafos_por_obra.items():

    net = Network(
        height="750px",
        width="100%",
        bgcolor="#ffffff",
        font_color="#000000",
        notebook=False
    )

    # Configuración física de la red para distribuir mejor los nodos.
    net.barnes_hut(
        gravity=-8000,
        central_gravity=0.3,
        spring_length=200,
        spring_strength=0.05,
        damping=0.09
    )

    centralidad_obra = df_centralidad[df_centralidad["obra"] == obra]
    centralidad_dict = dict(zip(
        centralidad_obra["personaje"],
        centralidad_obra["grado_centralidad"]
    ))

    # Los nodos más centrales se muestran con mayor tamaño.
    for nodo in G.nodes():
        centralidad = centralidad_dict.get(nodo, 0)
        tamano = 10 + centralidad * 80

        net.add_node(
            nodo,
            label=nodo,
            size=tamano,
            title=f"{nodo}<br>Centralidad: {centralidad}"
        )

    # El grosor/valor de la arista representa la cantidad de coocurrencias.
    for origen, destino, data in G.edges(data=True):
        peso = data.get("weight", 1)

        net.add_edge(
            origen,
            destino,
            value=peso,
            title=f"Coocurrencias: {peso}"
        )

    nombre_archivo = obra.lower().replace(" ", "_").replace(":", "").replace("/", "_")
    ruta_html = f"{RUTA_GRAFOS}/red_{nombre_archivo}.html"

    net.save_graph(ruta_html)

    archivos_grafos.append({
        "obra": obra,
        "archivo_html": ruta_html
    })

df_archivos_grafos = pd.DataFrame(archivos_grafos)

display(df_archivos_grafos)

obra,archivo_html
CELC_MVLL,/Volumes/workspace/default/mi_volumen/proyecto_nlp_libros/grafos/red_celc_mvll.html
CRDLI_IGDLV,/Volumes/workspace/default/mi_volumen/proyecto_nlp_libros/grafos/red_crdli_igdlv.html

In [0]:
# Visualización del primer grafo generado dentro del notebook.
archivo_html = df_archivos_grafos.iloc[0]["archivo_html"]

with open(archivo_html, "r", encoding="utf-8") as f:
    html_red = f.read()

displayHTML(html_red)

In [0]:
archivo_html = df_archivos_grafos.iloc[1]["archivo_html"]

with open(archivo_html, "r", encoding="utf-8") as f:
    html_red = f.read()

displayHTML(html_red)

In [0]:
# # Visualización de todos los grafos generados.
# for _, row in df_archivos_grafos.iterrows():
#     print("Obra:", row["obra"])

#     with open(row["archivo_html"], "r", encoding="utf-8") as f:
#         html_red = f.read()

#     displayHTML(f"<h3>{row['obra']}</h3>" + html_red)

# 18. Exportación de resultados

En esta sección se exportan las tablas principales del análisis a archivos CSV. Todas las rutas usan el volumen configurado en `RUTA_SALIDA`

In [0]:
# Se verifica la carpeta de salida configurada en la sección 5.
Path(RUTA_SALIDA).mkdir(parents=True, exist_ok=True)

print("Ruta de salida:", RUTA_SALIDA)

Ruta de salida: /Volumes/workspace/default/mi_volumen/proyecto_nlp_libros

In [0]:
df_entidades_limpio.to_csv(
    f"{RUTA_SALIDA}/entidades_limpias_completas.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Archivo exportado: entidades_limpias_completas.csv")

Archivo exportado: entidades_limpias_completas.csv

In [0]:
frecuencia_entidades_obra.to_csv(
    f"{RUTA_SALIDA}/frecuencia_entidades_obra.csv",
    index=False,
    encoding="utf-8-sig"
)

comparacion_tipos_obra.to_csv(
    f"{RUTA_SALIDA}/comparacion_tipos_obra.csv",
    index=False,
    encoding="utf-8-sig"
)

densidad_entidades_bloque.to_csv(
    f"{RUTA_SALIDA}/densidad_entidades_bloque.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Archivos de análisis exploratorio exportados.")

Archivos de análisis exploratorio exportados.

In [0]:
personajes_por_obra.to_csv(
    f"{RUTA_SALIDA}/personajes_por_obra.csv",
    index=False,
    encoding="utf-8-sig"
)

lugares_por_obra.to_csv(
    f"{RUTA_SALIDA}/lugares_por_obra.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Archivos de personajes y lugares exportados.")

Archivos de personajes y lugares exportados.

In [0]:
red_coocurrencia.to_csv(
    f"{RUTA_SALIDA}/red_coocurrencia_personajes.csv",
    index=False,
    encoding="utf-8-sig"
)

red_coocurrencia_filtrada.to_csv(
    f"{RUTA_SALIDA}/red_coocurrencia_personajes_filtrada.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Redes de coocurrencia exportadas.")

Redes de coocurrencia exportadas.

In [0]:
df_centralidad.to_csv(
    f"{RUTA_SALIDA}/metricas_centralidad_personajes.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Métricas de centralidad exportadas.")

Métricas de centralidad exportadas.

In [0]:
# Lista de archivos exportados en la carpeta principal del proyecto.
archivos_exportados = []

for nombre in sorted(os.listdir(RUTA_SALIDA)):
    ruta = os.path.join(RUTA_SALIDA, nombre)
    archivos_exportados.append({
        "nombre": nombre,
        "ruta": ruta,
        "tipo": "carpeta" if os.path.isdir(ruta) else "archivo"
    })

display(pd.DataFrame(archivos_exportados))

nombre,ruta,tipo
comparacion_tipos_obra.csv,/Volumes/workspace/default/mi_volumen/proyecto_nlp_libros/comparacion_tipos_obra.csv,archivo
densidad_entidades_bloque.csv,/Volumes/workspace/default/mi_volumen/proyecto_nlp_libros/densidad_entidades_bloque.csv,archivo
entidades_limpias_completas.csv,/Volumes/workspace/default/mi_volumen/proyecto_nlp_libros/entidades_limpias_completas.csv,archivo
frecuencia_entidades_obra.csv,/Volumes/workspace/default/mi_volumen/proyecto_nlp_libros/frecuencia_entidades_obra.csv,archivo
grafos,/Volumes/workspace/default/mi_volumen/proyecto_nlp_libros/grafos,carpeta
lugares_por_obra.csv,/Volumes/workspace/default/mi_volumen/proyecto_nlp_libros/lugares_por_obra.csv,archivo
metricas_centralidad_personajes.csv,/Volumes/workspace/default/mi_volumen/proyecto_nlp_libros/metricas_centralidad_personajes.csv,archivo
personajes_por_obra.csv,/Volumes/workspace/default/mi_volumen/proyecto_nlp_libros/personajes_por_obra.csv,archivo
red_coocurrencia_personajes.csv,/Volumes/workspace/default/mi_volumen/proyecto_nlp_libros/red_coocurrencia_personajes.csv,archivo
red_coocurrencia_personajes_filtrada.csv,/Volumes/workspace/default/mi_volumen/proyecto_nlp_libros/red_coocurrencia_personajes_filtrada.csv,archivo

In [0]:
spark_entidades = spark.createDataFrame(df_entidades_limpio)
spark_personajes = spark.createDataFrame(personajes_por_obra)
spark_lugares = spark.createDataFrame(lugares_por_obra)
spark_centralidad = spark.createDataFrame(df_centralidad)

display(spark_entidades.limit(10))

obra,titulo,autor,bloque_id,entidad,tipo,score,entidad_norm,entidad_canonica
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,La Catedral,LOC,0.9997674822807312,la catedral,La Catedral
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Mario Vargas Llosa,PER,0.9998625914255778,mario vargas llosa,Mario Vargas Llosa
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,La Crónica,LOC,0.9999179244041443,la crónica,La Crónica
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Santiago,PER,0.998166024684906,santiago,Santiago Zavala
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,avenida Tacna,LOC,0.9997281134128571,avenida tacna,avenida Tacna
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Perú,LOC,0.999950647354126,perú,Perú
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Wilson,PER,0.9970278143882751,wilson,Wilson
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Colmena,LOC,0.9996123909950256,colmena,Colmena
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Plaza San Martín,LOC,0.9999350309371948,plaza san martín,Plaza San Martín
CELC_MVLL,Conversación en La Catedral,Mario Vargas Llosa,1,Perú,LOC,0.9994574189186096,perú,Perú

In [0]:
spark_entidades.createOrReplaceTempView("vw_entidades_nlp")
spark_personajes.createOrReplaceTempView("vw_personajes_nlp")
spark_lugares.createOrReplaceTempView("vw_lugares_nlp")
spark_centralidad.createOrReplaceTempView("vw_centralidad_nlp")

In [0]:
%sql
SELECT 
    obra,
    tipo,
    COUNT(*) AS total_entidades
FROM vw_entidades_nlp
GROUP BY obra, tipo
ORDER BY obra, total_entidades DESC;

obra,tipo,total_entidades
CELC_MVLL,PER,10162
CELC_MVLL,LOC,1368
CELC_MVLL,ORG,624
CELC_MVLL,MISC,577
CRDLI_IGDLV,PER,3317
CRDLI_IGDLV,LOC,2698
CRDLI_IGDLV,MISC,2126
CRDLI_IGDLV,ORG,596

# 19. Interpretación de resultados

In [0]:
for obra in df_entidades_limpio["obra"].unique():
    print("=" * 90)
    print(f"OBRA: {obra}")
    print("=" * 90)

    total_entidades = len(df_entidades_limpio[df_entidades_limpio["obra"] == obra])
    total_personajes = len(df_personajes[df_personajes["obra"] == obra])
    total_lugares = len(df_lugares[df_lugares["obra"] == obra])

    print(f"Total de entidades detectadas: {total_entidades}")
    print(f"Total de menciones de personajes/personas: {total_personajes}")
    print(f"Total de menciones de lugares/escenarios: {total_lugares}")

    print("\nTop 5 personajes:")
    display(
        personajes_por_obra[personajes_por_obra["obra"] == obra]
        .head(5)
    )

    print("\nTop 5 lugares:")
    display(
        lugares_por_obra[lugares_por_obra["obra"] == obra]
        .head(5)
    )

==========================================================================================
OBRA: CELC_MVLL
==========================================================================================
Total de entidades detectadas: 12731
Total de menciones de personajes/personas: 10162
Total de menciones de lugares/escenarios: 1368

Top 5 personajes:

obra,entidad_canonica,frecuencia,score_promedio,bloques_distintos,densidad_narrativa
CELC_MVLL,Santiago Zavala,1154,0.9986,177,6.52
CELC_MVLL,Ambrosio Pardo,799,0.9993,198,4.04
CELC_MVLL,Cayo Bermúdez,664,0.959,149,4.46
CELC_MVLL,Amalia Landa,631,0.9928,96,6.57
CELC_MVLL,Queta,407,0.987,80,5.09

Top 5 lugares:

obra,entidad_norm,frecuencia,score_promedio,bloques_distintos
CELC_MVLL,lima,107,0.9998,77
CELC_MVLL,arequipa,58,0.9982,31
CELC_MVLL,perú,49,0.9997,39
CELC_MVLL,pucallpa,49,0.9909,27
CELC_MVLL,san marcos,46,0.9704,26

==========================================================================================
OBRA: CRDLI_IGDLV
==========================================================================================
Total de entidades detectadas: 8737
Total de menciones de personajes/personas: 3317
Total de menciones de lugares/escenarios: 2698

Top 5 personajes:

obra,entidad_canonica,frecuencia,score_promedio,bloques_distintos,densidad_narrativa
CRDLI_IGDLV,Inca,642,0.94,204,3.15
CRDLI_IGDLV,Rey,235,0.9728,144,1.63
CRDLI_IGDLV,Reyes,189,0.9695,121,1.56
CRDLI_IGDLV,Sol,132,0.8293,68,1.94
CRDLI_IGDLV,Incas,107,0.76,71,1.51

Top 5 lugares:

obra,entidad_norm,frecuencia,score_promedio,bloques_distintos
CRDLI_IGDLV,perú,363,0.9968,188
CRDLI_IGDLV,cozco,354,0.9915,191
CRDLI_IGDLV,españa,163,0.9992,90
CRDLI_IGDLV,chili,54,0.9903,26
CRDLI_IGDLV,quitu,53,0.9999,32

In [0]:
for obra in df_centralidad["obra"].unique():
    print("=" * 90)
    print(f"PERSONAJES CENTRALES EN: {obra}")
    print("=" * 90)

    data_obra = (
        df_centralidad[df_centralidad["obra"] == obra]
        .sort_values("grado_centralidad", ascending=False)
        .head(5)
    )

    for _, row in data_obra.iterrows():
        print(
            f"{row['personaje']} destaca por su nivel de conexión en la red, "
            f"con un grado de centralidad de {row['grado_centralidad']} "
            f"y un peso total de relaciones de {row['peso_total_relaciones']}."
        )

    print()

==========================================================================================
PERSONAJES CENTRALES EN: CELC_MVLL
==========================================================================================
Ambrosio Pardo destaca por su nivel de conexión en la red, con un grado de centralidad de 0.761 y un peso total de relaciones de 1637.
Cayo Bermúdez destaca por su nivel de conexión en la red, con un grado de centralidad de 0.6585 y un peso total de relaciones de 1360.
Santiago Zavala destaca por su nivel de conexión en la red, con un grado de centralidad de 0.639 y un peso total de relaciones de 1359.
Fermín Zavala destaca por su nivel de conexión en la red, con un grado de centralidad de 0.5073 y un peso total de relaciones de 977.
don destaca por su nivel de conexión en la red, con un grado de centralidad de 0.4439 y un peso total de relaciones de 726.

==========================================================================================
PERSONAJES CENTRALES EN: CRDLI_IGDLV
==========================================================================================
Inca destaca por su nivel de conexión en la red, con un grado de centralidad de 0.7572 y un peso total de relaciones de 937.
Rey destaca por su nivel de conexión en la red, con un grado de centralidad de 0.5896 y un peso total de relaciones de 667.
Reyes destaca por su nivel de conexión en la red, con un grado de centralidad de 0.4855 y un peso total de relaciones de 583.
Incas destaca por su nivel de conexión en la red, con un grado de centralidad de 0.3064 y un peso total de relaciones de 321.
Huayna Cápac destaca por su nivel de conexión en la red, con un grado de centralidad de 0.2659 y un peso total de relaciones de 235.

In [0]:
for obra in lugares_por_obra["obra"].unique():
    print("=" * 90)
    print(f"LUGARES PREDOMINANTES EN: {obra}")
    print("=" * 90)

    data_obra = lugares_por_obra[
        lugares_por_obra["obra"] == obra
    ].head(5)

    for _, row in data_obra.iterrows():
        print(
            f"{row['entidad_norm']} aparece con una frecuencia de "
            f"{row['frecuencia']} menciones, distribuidas en "
            f"{row['bloques_distintos']} bloques distintos."
        )

    print()

==========================================================================================
LUGARES PREDOMINANTES EN: CELC_MVLL
==========================================================================================
lima aparece con una frecuencia de 107 menciones, distribuidas en 77 bloques distintos.
arequipa aparece con una frecuencia de 58 menciones, distribuidas en 31 bloques distintos.
perú aparece con una frecuencia de 49 menciones, distribuidas en 39 bloques distintos.
pucallpa aparece con una frecuencia de 49 menciones, distribuidas en 27 bloques distintos.
san marcos aparece con una frecuencia de 46 menciones, distribuidas en 26 bloques distintos.

==========================================================================================
LUGARES PREDOMINANTES EN: CRDLI_IGDLV
==========================================================================================
perú aparece con una frecuencia de 363 menciones, distribuidas en 188 bloques distintos.
cozco aparece con una frecuencia de 354 menciones, distribuidas en 191 bloques distintos.
españa aparece con una frecuencia de 163 menciones, distribuidas en 90 bloques distintos.
chili aparece con una frecuencia de 54 menciones, distribuidas en 26 bloques distintos.
quitu aparece con una frecuencia de 53 menciones, distribuidas en 32 bloques distintos.

In [0]:
for obra, G in grafos_por_obra.items():
    print("=" * 90)
    print(f"RED DE COOCCURRENCIA EN: {obra}")
    print("=" * 90)

    print(f"Número de personajes en la red: {G.number_of_nodes()}")
    print(f"Número de relaciones entre personajes: {G.number_of_edges()}")

    if G.number_of_nodes() > 0:
        densidad = nx.density(G)
        print(f"Densidad de la red: {round(densidad, 4)}")

    print()

==========================================================================================
RED DE COOCCURRENCIA EN: CELC_MVLL
==========================================================================================
Número de personajes en la red: 206
Número de relaciones entre personajes: 2103
Densidad de la red: 0.0996

==========================================================================================
RED DE COOCCURRENCIA EN: CRDLI_IGDLV
==========================================================================================
Número de personajes en la red: 174
Número de relaciones entre personajes: 715
Densidad de la red: 0.0475

La red de coocurrencia se construyó a partir de bloques textuales de tamaño fijo, por lo que una relación entre personajes indica proximidad textual dentro del mismo bloque, no necesariamente interacción narrativa directa. Por ello, las relaciones detectadas deben interpretarse como asociaciones aproximadas y no como vínculos confirmados entre personajes.

**Interpretación general de resultados**

El análisis de entidades nombradas permitió identificar personas, lugares, organizaciones y otras referencias relevantes dentro de las dos obras estudiadas. Las entidades clasificadas como personas fueron utilizadas como una aproximación inicial a los personajes o figuras mencionadas, mientras que las entidades de tipo lugar permitieron reconocer escenarios o espacios geográficos presentes en el corpus.

La comparación entre obras permite observar diferencias en la distribución de entidades. Una obra puede presentar mayor concentración de personajes, mientras que otra puede destacar por la presencia de lugares, referencias históricas o instituciones. Esta diferencia es importante porque refleja la naturaleza textual de cada obra: una puede tener una orientación más narrativa y otra una orientación más histórica o descriptiva.

Además, la construcción de redes de coocurrencia permitió analizar qué personajes aparecen juntos dentro de los mismos bloques textuales. A partir de estas relaciones, las métricas de centralidad ayudaron a identificar personajes con mayor peso estructural dentro de cada obra. Sin embargo, estos resultados deben interpretarse con cuidado, ya que la extracción automática de entidades puede presentar errores, especialmente en textos literarios, históricos o con formas antiguas del español.

# 20. Conclusiones

El procesamiento computacional del corpus permitió extraer y organizar información relevante sobre entidades nombradas presentes en las obras analizadas. Mediante el uso de Flair para el reconocimiento de entidades y spaCy como apoyo lingüístico, fue posible identificar menciones asociadas a personas, lugares, organizaciones y otras referencias textuales. Esta información sirvió como base para construir una lectura cuantitativa inicial de los personajes, escenarios y relaciones internas de cada obra.

El análisis de personajes mostró qué nombres aparecen con mayor frecuencia y cuáles tienen mayor presencia en distintos bloques del texto. A partir de la red de coocurrencia, también fue posible observar qué personajes tienden a aparecer juntos y cuáles ocupan posiciones más centrales dentro de la estructura textual. Las métricas de centralidad permitieron complementar la frecuencia simple, ya que un personaje no solo puede ser importante por aparecer muchas veces, sino también por conectar diferentes grupos de personajes.

El análisis de lugares y escenarios permitió reconocer los espacios más mencionados dentro de cada obra. Esto resulta especialmente útil para comparar textos literarios e históricos, ya que los lugares pueden funcionar como escenarios narrativos, referencias geográficas o marcas contextuales. En conjunto, estos resultados muestran que las técnicas de NLP pueden apoyar el análisis literario al ofrecer evidencia cuantitativa sobre patrones de aparición, distribución y relación entre entidades.

Finalmente, es importante señalar que los resultados no deben considerarse definitivos sin una revisión humana. Los modelos de reconocimiento de entidades pueden confundir nombres, lugares u organizaciones, sobre todo en textos con lenguaje literario, histórico o antiguo. Por ello, este análisis debe entenderse como una herramienta de apoyo para la interpretación, no como un reemplazo de la lectura crítica de las obras.